// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/looplj/axonhub/internal/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/apikey"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/channelmodelprice"
	"github.com/looplj/axonhub/internal/ent/channelmodelpriceversion"
	"github.com/looplj/axonhub/internal/ent/channeloverridetemplate"
	"github.com/looplj/axonhub/internal/ent/channelprobe"
	"github.com/looplj/axonhub/internal/ent/model"
	"github.com/looplj/axonhub/internal/ent/providerquotastatus"
	"github.com/looplj/axonhub/internal/ent/request"
	"github.com/looplj/axonhub/internal/ent/requestexecution"
	"github.com/looplj/axonhub/internal/ent/system"
	"github.com/looplj/axonhub/internal/ent/usagelog"
	"github.com/looplj/axonhub/internal/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// APIKey is the client for interacting with the APIKey builders.
	APIKey *APIKeyClient
	// Channel is the client for interacting with the Channel builders.
	Channel *ChannelClient
	// ChannelModelPrice is the client for interacting with the ChannelModelPrice builders.
	ChannelModelPrice *ChannelModelPriceClient
	// ChannelModelPriceVersion is the client for interacting with the ChannelModelPriceVersion builders.
	ChannelModelPriceVersion *ChannelModelPriceVersionClient
	// ChannelOverrideTemplate is the client for interacting with the ChannelOverrideTemplate builders.
	ChannelOverrideTemplate *ChannelOverrideTemplateClient
	// ChannelProbe is the client for interacting with the ChannelProbe builders.
	ChannelProbe *ChannelProbeClient
	// Model is the client for interacting with the Model builders.
	Model *ModelClient
	// ProviderQuotaStatus is the client for interacting with the ProviderQuotaStatus builders.
	ProviderQuotaStatus *ProviderQuotaStatusClient
	// Request is the client for interacting with the Request builders.
	Request *RequestClient
	// RequestExecution is the client for interacting with the RequestExecution builders.
	RequestExecution *RequestExecutionClient
	// System is the client for interacting with the System builders.
	System *SystemClient
	// UsageLog is the client for interacting with the UsageLog builders.
	UsageLog *UsageLogClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// additional fields for node api
	tables tables
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.APIKey = NewAPIKeyClient(c.config)
	c.Channel = NewChannelClient(c.config)
	c.ChannelModelPrice = NewChannelModelPriceClient(c.config)
	c.ChannelModelPriceVersion = NewChannelModelPriceVersionClient(c.config)
	c.ChannelOverrideTemplate = NewChannelOverrideTemplateClient(c.config)
	c.ChannelProbe = NewChannelProbeClient(c.config)
	c.Model = NewModelClient(c.config)
	c.ProviderQuotaStatus = NewProviderQuotaStatusClient(c.config)
	c.Request = NewRequestClient(c.config)
	c.RequestExecution = NewRequestExecutionClient(c.config)
	c.System = NewSystemClient(c.config)
	c.UsageLog = NewUsageLogClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                      ctx,
		config:                   cfg,
		APIKey:                   NewAPIKeyClient(cfg),
		Channel:                  NewChannelClient(cfg),
		ChannelModelPrice:        NewChannelModelPriceClient(cfg),
		ChannelModelPriceVersion: NewChannelModelPriceVersionClient(cfg),
		ChannelOverrideTemplate:  NewChannelOverrideTemplateClient(cfg),
		ChannelProbe:             NewChannelProbeClient(cfg),
		Model:                    NewModelClient(cfg),
		ProviderQuotaStatus:      NewProviderQuotaStatusClient(cfg),
		Request:                  NewRequestClient(cfg),
		RequestExecution:         NewRequestExecutionClient(cfg),
		System:                   NewSystemClient(cfg),
		UsageLog:                 NewUsageLogClient(cfg),
		User:                     NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                      ctx,
		config:                   cfg,
		APIKey:                   NewAPIKeyClient(cfg),
		Channel:                  NewChannelClient(cfg),
		ChannelModelPrice:        NewChannelModelPriceClient(cfg),
		ChannelModelPriceVersion: NewChannelModelPriceVersionClient(cfg),
		ChannelOverrideTemplate:  NewChannelOverrideTemplateClient(cfg),
		ChannelProbe:             NewChannelProbeClient(cfg),
		Model:                    NewModelClient(cfg),
		ProviderQuotaStatus:      NewProviderQuotaStatusClient(cfg),
		Request:                  NewRequestClient(cfg),
		RequestExecution:         NewRequestExecutionClient(cfg),
		System:                   NewSystemClient(cfg),
		UsageLog:                 NewUsageLogClient(cfg),
		User:                     NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		APIKey.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.APIKey, c.Channel, c.ChannelModelPrice, c.ChannelModelPriceVersion,
		c.ChannelOverrideTemplate, c.ChannelProbe, c.Model, c.ProviderQuotaStatus,
		c.Request, c.RequestExecution, c.System, c.UsageLog, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.APIKey, c.Channel, c.ChannelModelPrice, c.ChannelModelPriceVersion,
		c.ChannelOverrideTemplate, c.ChannelProbe, c.Model, c.ProviderQuotaStatus,
		c.Request, c.RequestExecution, c.System, c.UsageLog, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *APIKeyMutation:
		return c.APIKey.mutate(ctx, m)
	case *ChannelMutation:
		return c.Channel.mutate(ctx, m)
	case *ChannelModelPriceMutation:
		return c.ChannelModelPrice.mutate(ctx, m)
	case *ChannelModelPriceVersionMutation:
		return c.ChannelModelPriceVersion.mutate(ctx, m)
	case *ChannelOverrideTemplateMutation:
		return c.ChannelOverrideTemplate.mutate(ctx, m)
	case *ChannelProbeMutation:
		return c.ChannelProbe.mutate(ctx, m)
	case *ModelMutation:
		return c.Model.mutate(ctx, m)
	case *ProviderQuotaStatusMutation:
		return c.ProviderQuotaStatus.mutate(ctx, m)
	case *RequestMutation:
		return c.Request.mutate(ctx, m)
	case *RequestExecutionMutation:
		return c.RequestExecution.mutate(ctx, m)
	case *SystemMutation:
		return c.System.mutate(ctx, m)
	case *UsageLogMutation:
		return c.UsageLog.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// APIKeyClient is a client for the APIKey schema.
type APIKeyClient struct {
	config
}

// NewAPIKeyClient returns a client for the APIKey from the given config.
func NewAPIKeyClient(c config) *APIKeyClient {
	return &APIKeyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `apikey.Hooks(f(g(h())))`.
func (c *APIKeyClient) Use(hooks ...Hook) {
	c.hooks.APIKey = append(c.hooks.APIKey, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `apikey.Intercept(f(g(h())))`.
func (c *APIKeyClient) Intercept(interceptors ...Interceptor) {
	c.inters.APIKey = append(c.inters.APIKey, interceptors...)
}

// Create returns a builder for creating a APIKey entity.
func (c *APIKeyClient) Create() *APIKeyCreate {
	mutation := newAPIKeyMutation(c.config, OpCreate)
	return &APIKeyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of APIKey entities.
func (c *APIKeyClient) CreateBulk(builders ...*APIKeyCreate) *APIKeyCreateBulk {
	return &APIKeyCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *APIKeyClient) MapCreateBulk(slice any, setFunc func(*APIKeyCreate, int)) *APIKeyCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &APIKeyCreateBulk{err: fmt.Errorf("calling to APIKeyClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*APIKeyCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &APIKeyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for APIKey.
func (c *APIKeyClient) Update() *APIKeyUpdate {
	mutation := newAPIKeyMutation(c.config, OpUpdate)
	return &APIKeyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *APIKeyClient) UpdateOne(_m *APIKey) *APIKeyUpdateOne {
	mutation := newAPIKeyMutation(c.config, OpUpdateOne, withAPIKey(_m))
	return &APIKeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *APIKeyClient) UpdateOneID(id int) *APIKeyUpdateOne {
	mutation := newAPIKeyMutation(c.config, OpUpdateOne, withAPIKeyID(id))
	return &APIKeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for APIKey.
func (c *APIKeyClient) Delete() *APIKeyDelete {
	mutation := newAPIKeyMutation(c.config, OpDelete)
	return &APIKeyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *APIKeyClient) DeleteOne(_m *APIKey) *APIKeyDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *APIKeyClient) DeleteOneID(id int) *APIKeyDeleteOne {
	builder := c.Delete().Where(apikey.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &APIKeyDeleteOne{builder}
}

// Query returns a query builder for APIKey.
func (c *APIKeyClient) Query() *APIKeyQuery {
	return &APIKeyQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAPIKey},
		inters: c.Interceptors(),
	}
}

// Get returns a APIKey entity by its id.
func (c *APIKeyClient) Get(ctx context.Context, id int) (*APIKey, error) {
	return c.Query().Where(apikey.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *APIKeyClient) GetX(ctx context.Context, id int) *APIKey {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRequests queries the requests edge of a APIKey.
func (c *APIKeyClient) QueryRequests(_m *APIKey) *RequestQuery {
	query := (&RequestClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(apikey.Table, apikey.FieldID, id),
			sqlgraph.To(request.Table, request.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, apikey.RequestsTable, apikey.RequestsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *APIKeyClient) Hooks() []Hook {
	hooks := c.hooks.APIKey
	return append(hooks[:len(hooks):len(hooks)], apikey.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *APIKeyClient) Interceptors() []Interceptor {
	inters := c.inters.APIKey
	return append(inters[:len(inters):len(inters)], apikey.Interceptors[:]...)
}

func (c *APIKeyClient) mutate(ctx context.Context, m *APIKeyMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&APIKeyCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&APIKeyUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&APIKeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&APIKeyDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown APIKey mutation op: %q", m.Op())
	}
}

// ChannelClient is a client for the Channel schema.
type ChannelClient struct {
	config
}

// NewChannelClient returns a client for the Channel from the given config.
func NewChannelClient(c config) *ChannelClient {
	return &ChannelClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `channel.Hooks(f(g(h())))`.
func (c *ChannelClient) Use(hooks ...Hook) {
	c.hooks.Channel = append(c.hooks.Channel, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `channel.Intercept(f(g(h())))`.
func (c *ChannelClient) Intercept(interceptors ...Interceptor) {
	c.inters.Channel = append(c.inters.Channel, interceptors...)
}

// Create returns a builder for creating a Channel entity.
func (c *ChannelClient) Create() *ChannelCreate {
	mutation := newChannelMutation(c.config, OpCreate)
	return &ChannelCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Channel entities.
func (c *ChannelClient) CreateBulk(builders ...*ChannelCreate) *ChannelCreateBulk {
	return &ChannelCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChannelClient) MapCreateBulk(slice any, setFunc func(*ChannelCreate, int)) *ChannelCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChannelCreateBulk{err: fmt.Errorf("calling to ChannelClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChannelCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChannelCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Channel.
func (c *ChannelClient) Update() *ChannelUpdate {
	mutation := newChannelMutation(c.config, OpUpdate)
	return &ChannelUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChannelClient) UpdateOne(_m *Channel) *ChannelUpdateOne {
	mutation := newChannelMutation(c.config, OpUpdateOne, withChannel(_m))
	return &ChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChannelClient) UpdateOneID(id int) *ChannelUpdateOne {
	mutation := newChannelMutation(c.config, OpUpdateOne, withChannelID(id))
	return &ChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Channel.
func (c *ChannelClient) Delete() *ChannelDelete {
	mutation := newChannelMutation(c.config, OpDelete)
	return &ChannelDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChannelClient) DeleteOne(_m *Channel) *ChannelDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChannelClient) DeleteOneID(id int) *ChannelDeleteOne {
	builder := c.Delete().Where(channel.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChannelDeleteOne{builder}
}

// Query returns a query builder for Channel.
func (c *ChannelClient) Query() *ChannelQuery {
	return &ChannelQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChannel},
		inters: c.Interceptors(),
	}
}

// Get returns a Channel entity by its id.
func (c *ChannelClient) Get(ctx context.Context, id int) (*Channel, error) {
	return c.Query().Where(channel.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChannelClient) GetX(ctx context.Context, id int) *Channel {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRequests queries the requests edge of a Channel.
func (c *ChannelClient) QueryRequests(_m *Channel) *RequestQuery {
	query := (&RequestClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, id),
			sqlgraph.To(request.Table, request.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channel.RequestsTable, channel.RequestsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryExecutions queries the executions edge of a Channel.
func (c *ChannelClient) QueryExecutions(_m *Channel) *RequestExecutionQuery {
	query := (&RequestExecutionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, id),
			sqlgraph.To(requestexecution.Table, requestexecution.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channel.ExecutionsTable, channel.ExecutionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUsageLogs queries the usage_logs edge of a Channel.
func (c *ChannelClient) QueryUsageLogs(_m *Channel) *UsageLogQuery {
	query := (&UsageLogClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, id),
			sqlgraph.To(usagelog.Table, usagelog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channel.UsageLogsTable, channel.UsageLogsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChannelProbes queries the channel_probes edge of a Channel.
func (c *ChannelClient) QueryChannelProbes(_m *Channel) *ChannelProbeQuery {
	query := (&ChannelProbeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, id),
			sqlgraph.To(channelprobe.Table, channelprobe.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channel.ChannelProbesTable, channel.ChannelProbesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChannelModelPrices queries the channel_model_prices edge of a Channel.
func (c *ChannelClient) QueryChannelModelPrices(_m *Channel) *ChannelModelPriceQuery {
	query := (&ChannelModelPriceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, id),
			sqlgraph.To(channelmodelprice.Table, channelmodelprice.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channel.ChannelModelPricesTable, channel.ChannelModelPricesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryProviderQuotaStatus queries the provider_quota_status edge of a Channel.
func (c *ChannelClient) QueryProviderQuotaStatus(_m *Channel) *ProviderQuotaStatusQuery {
	query := (&ProviderQuotaStatusClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, id),
			sqlgraph.To(providerquotastatus.Table, providerquotastatus.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, channel.ProviderQuotaStatusTable, channel.ProviderQuotaStatusColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ChannelClient) Hooks() []Hook {
	hooks := c.hooks.Channel
	return append(hooks[:len(hooks):len(hooks)], channel.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *ChannelClient) Interceptors() []Interceptor {
	inters := c.inters.Channel
	return append(inters[:len(inters):len(inters)], channel.Interceptors[:]...)
}

func (c *ChannelClient) mutate(ctx context.Context, m *ChannelMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChannelCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChannelUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChannelDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Channel mutation op: %q", m.Op())
	}
}

// ChannelModelPriceClient is a client for the ChannelModelPrice schema.
type ChannelModelPriceClient struct {
	config
}

// NewChannelModelPriceClient returns a client for the ChannelModelPrice from the given config.
func NewChannelModelPriceClient(c config) *ChannelModelPriceClient {
	return &ChannelModelPriceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `channelmodelprice.Hooks(f(g(h())))`.
func (c *ChannelModelPriceClient) Use(hooks ...Hook) {
	c.hooks.ChannelModelPrice = append(c.hooks.ChannelModelPrice, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `channelmodelprice.Intercept(f(g(h())))`.
func (c *ChannelModelPriceClient) Intercept(interceptors ...Interceptor) {
	c.inters.ChannelModelPrice = append(c.inters.ChannelModelPrice, interceptors...)
}

// Create returns a builder for creating a ChannelModelPrice entity.
func (c *ChannelModelPriceClient) Create() *ChannelModelPriceCreate {
	mutation := newChannelModelPriceMutation(c.config, OpCreate)
	return &ChannelModelPriceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ChannelModelPrice entities.
func (c *ChannelModelPriceClient) CreateBulk(builders ...*ChannelModelPriceCreate) *ChannelModelPriceCreateBulk {
	return &ChannelModelPriceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChannelModelPriceClient) MapCreateBulk(slice any, setFunc func(*ChannelModelPriceCreate, int)) *ChannelModelPriceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChannelModelPriceCreateBulk{err: fmt.Errorf("calling to ChannelModelPriceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChannelModelPriceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChannelModelPriceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ChannelModelPrice.
func (c *ChannelModelPriceClient) Update() *ChannelModelPriceUpdate {
	mutation := newChannelModelPriceMutation(c.config, OpUpdate)
	return &ChannelModelPriceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChannelModelPriceClient) UpdateOne(_m *ChannelModelPrice) *ChannelModelPriceUpdateOne {
	mutation := newChannelModelPriceMutation(c.config, OpUpdateOne, withChannelModelPrice(_m))
	return &ChannelModelPriceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChannelModelPriceClient) UpdateOneID(id int) *ChannelModelPriceUpdateOne {
	mutation := newChannelModelPriceMutation(c.config, OpUpdateOne, withChannelModelPriceID(id))
	return &ChannelModelPriceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ChannelModelPrice.
func (c *ChannelModelPriceClient) Delete() *ChannelModelPriceDelete {
	mutation := newChannelModelPriceMutation(c.config, OpDelete)
	return &ChannelModelPriceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChannelModelPriceClient) DeleteOne(_m *ChannelModelPrice) *ChannelModelPriceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChannelModelPriceClient) DeleteOneID(id int) *ChannelModelPriceDeleteOne {
	builder := c.Delete().Where(channelmodelprice.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChannelModelPriceDeleteOne{builder}
}

// Query returns a query builder for ChannelModelPrice.
func (c *ChannelModelPriceClient) Query() *ChannelModelPriceQuery {
	return &ChannelModelPriceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChannelModelPrice},
		inters: c.Interceptors(),
	}
}

// Get returns a ChannelModelPrice entity by its id.
func (c *ChannelModelPriceClient) Get(ctx context.Context, id int) (*ChannelModelPrice, error) {
	return c.Query().Where(channelmodelprice.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChannelModelPriceClient) GetX(ctx context.Context, id int) *ChannelModelPrice {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryChannel queries the channel edge of a ChannelModelPrice.
func (c *ChannelModelPriceClient) QueryChannel(_m *ChannelModelPrice) *ChannelQuery {
	query := (&ChannelClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channelmodelprice.Table, channelmodelprice.FieldID, id),
			sqlgraph.To(channel.Table, channel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, channelmodelprice.ChannelTable, channelmodelprice.ChannelColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryVersions queries the versions edge of a ChannelModelPrice.
func (c *ChannelModelPriceClient) QueryVersions(_m *ChannelModelPrice) *ChannelModelPriceVersionQuery {
	query := (&ChannelModelPriceVersionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channelmodelprice.Table, channelmodelprice.FieldID, id),
			sqlgraph.To(channelmodelpriceversion.Table, channelmodelpriceversion.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channelmodelprice.VersionsTable, channelmodelprice.VersionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ChannelModelPriceClient) Hooks() []Hook {
	hooks := c.hooks.ChannelModelPrice
	return append(hooks[:len(hooks):len(hooks)], channelmodelprice.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *ChannelModelPriceClient) Interceptors() []Interceptor {
	inters := c.inters.ChannelModelPrice
	return append(inters[:len(inters):len(inters)], channelmodelprice.Interceptors[:]...)
}

func (c *ChannelModelPriceClient) mutate(ctx context.Context, m *ChannelModelPriceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChannelModelPriceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChannelModelPriceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChannelModelPriceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChannelModelPriceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ChannelModelPrice mutation op: %q", m.Op())
	}
}

// ChannelModelPriceVersionClient is a client for the ChannelModelPriceVersion schema.
type ChannelModelPriceVersionClient struct {
	config
}

// NewChannelModelPriceVersionClient returns a client for the ChannelModelPriceVersion from the given config.
func NewChannelModelPriceVersionClient(c config) *ChannelModelPriceVersionClient {
	return &ChannelModelPriceVersionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `channelmodelpriceversion.Hooks(f(g(h())))`.
func (c *ChannelModelPriceVersionClient) Use(hooks ...Hook) {
	c.hooks.ChannelModelPriceVersion = append(c.hooks.ChannelModelPriceVersion, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `channelmodelpriceversion.Intercept(f(g(h())))`.
func (c *ChannelModelPriceVersionClient) Intercept(interceptors ...Interceptor) {
	c.inters.ChannelModelPriceVersion = append(c.inters.ChannelModelPriceVersion, interceptors...)
}

// Create returns a builder for creating a ChannelModelPriceVersion entity.
func (c *ChannelModelPriceVersionClient) Create() *ChannelModelPriceVersionCreate {
	mutation := newChannelModelPriceVersionMutation(c.config, OpCreate)
	return &ChannelModelPriceVersionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ChannelModelPriceVersion entities.
func (c *ChannelModelPriceVersionClient) CreateBulk(builders ...*ChannelModelPriceVersionCreate) *ChannelModelPriceVersionCreateBulk {
	return &ChannelModelPriceVersionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChannelModelPriceVersionClient) MapCreateBulk(slice any, setFunc func(*ChannelModelPriceVersionCreate, int)) *ChannelModelPriceVersionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChannelModelPriceVersionCreateBulk{err: fmt.Errorf("calling to ChannelModelPriceVersionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChannelModelPriceVersionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChannelModelPriceVersionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ChannelModelPriceVersion.
func (c *ChannelModelPriceVersionClient) Update() *ChannelModelPriceVersionUpdate {
	mutation := newChannelModelPriceVersionMutation(c.config, OpUpdate)
	return &ChannelModelPriceVersionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChannelModelPriceVersionClient) UpdateOne(_m *ChannelModelPriceVersion) *ChannelModelPriceVersionUpdateOne {
	mutation := newChannelModelPriceVersionMutation(c.config, OpUpdateOne, withChannelModelPriceVersion(_m))
	return &ChannelModelPriceVersionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChannelModelPriceVersionClient) UpdateOneID(id int) *ChannelModelPriceVersionUpdateOne {
	mutation := newChannelModelPriceVersionMutation(c.config, OpUpdateOne, withChannelModelPriceVersionID(id))
	return &ChannelModelPriceVersionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ChannelModelPriceVersion.
func (c *ChannelModelPriceVersionClient) Delete() *ChannelModelPriceVersionDelete {
	mutation := newChannelModelPriceVersionMutation(c.config, OpDelete)
	return &ChannelModelPriceVersionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChannelModelPriceVersionClient) DeleteOne(_m *ChannelModelPriceVersion) *ChannelModelPriceVersionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChannelModelPriceVersionClient) DeleteOneID(id int) *ChannelModelPriceVersionDeleteOne {
	builder := c.Delete().Where(channelmodelpriceversion.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChannelModelPriceVersionDeleteOne{builder}
}

// Query returns a query builder for ChannelModelPriceVersion.
func (c *ChannelModelPriceVersionClient) Query() *ChannelModelPriceVersionQuery {
	return &ChannelModelPriceVersionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChannelModelPriceVersion},
		inters: c.Interceptors(),
	}
}

// Get returns a ChannelModelPriceVersion entity by its id.
func (c *ChannelModelPriceVersionClient) Get(ctx context.Context, id int) (*ChannelModelPriceVersion, error) {
	return c.Query().Where(channelmodelpriceversion.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChannelModelPriceVersionClient) GetX(ctx context.Context, id int) *ChannelModelPriceVersion {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryChannelModelPrice queries the channel_model_price edge of a ChannelModelPriceVersion.
func (c *ChannelModelPriceVersionClient) QueryChannelModelPrice(_m *ChannelModelPriceVersion) *ChannelModelPriceQuery {
	query := (&ChannelModelPriceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channelmodelpriceversion.Table, channelmodelpriceversion.FieldID, id),
			sqlgraph.To(channelmodelprice.Table, channelmodelprice.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, channelmodelpriceversion.ChannelModelPriceTable, channelmodelpriceversion.ChannelModelPriceColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ChannelModelPriceVersionClient) Hooks() []Hook {
	hooks := c.hooks.ChannelModelPriceVersion
	return append(hooks[:len(hooks):len(hooks)], channelmodelpriceversion.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *ChannelModelPriceVersionClient) Interceptors() []Interceptor {
	return c.inters.ChannelModelPriceVersion
}

func (c *ChannelModelPriceVersionClient) mutate(ctx context.Context, m *ChannelModelPriceVersionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChannelModelPriceVersionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChannelModelPriceVersionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChannelModelPriceVersionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChannelModelPriceVersionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ChannelModelPriceVersion mutation op: %q", m.Op())
	}
}

// ChannelOverrideTemplateClient is a client for the ChannelOverrideTemplate schema.
type ChannelOverrideTemplateClient struct {
	config
}

// NewChannelOverrideTemplateClient returns a client for the ChannelOverrideTemplate from the given config.
func NewChannelOverrideTemplateClient(c config) *ChannelOverrideTemplateClient {
	return &ChannelOverrideTemplateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `channeloverridetemplate.Hooks(f(g(h())))`.
func (c *ChannelOverrideTemplateClient) Use(hooks ...Hook) {
	c.hooks.ChannelOverrideTemplate = append(c.hooks.ChannelOverrideTemplate, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `channeloverridetemplate.Intercept(f(g(h())))`.
func (c *ChannelOverrideTemplateClient) Intercept(interceptors ...Interceptor) {
	c.inters.ChannelOverrideTemplate = append(c.inters.ChannelOverrideTemplate, interceptors...)
}

// Create returns a builder for creating a ChannelOverrideTemplate entity.
func (c *ChannelOverrideTemplateClient) Create() *ChannelOverrideTemplateCreate {
	mutation := newChannelOverrideTemplateMutation(c.config, OpCreate)
	return &ChannelOverrideTemplateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ChannelOverrideTemplate entities.
func (c *ChannelOverrideTemplateClient) CreateBulk(builders ...*ChannelOverrideTemplateCreate) *ChannelOverrideTemplateCreateBulk {
	return &ChannelOverrideTemplateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChannelOverrideTemplateClient) MapCreateBulk(slice any, setFunc func(*ChannelOverrideTemplateCreate, int)) *ChannelOverrideTemplateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChannelOverrideTemplateCreateBulk{err: fmt.Errorf("calling to ChannelOverrideTemplateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChannelOverrideTemplateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChannelOverrideTemplateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ChannelOverrideTemplate.
func (c *ChannelOverrideTemplateClient) Update() *ChannelOverrideTemplateUpdate {
	mutation := newChannelOverrideTemplateMutation(c.config, OpUpdate)
	return &ChannelOverrideTemplateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChannelOverrideTemplateClient) UpdateOne(_m *ChannelOverrideTemplate) *ChannelOverrideTemplateUpdateOne {
	mutation := newChannelOverrideTemplateMutation(c.config, OpUpdateOne, withChannelOverrideTemplate(_m))
	return &ChannelOverrideTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChannelOverrideTemplateClient) UpdateOneID(id int) *ChannelOverrideTemplateUpdateOne {
	mutation := newChannelOverrideTemplateMutation(c.config, OpUpdateOne, withChannelOverrideTemplateID(id))
	return &ChannelOverrideTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ChannelOverrideTemplate.
func (c *ChannelOverrideTemplateClient) Delete() *ChannelOverrideTemplateDelete {
	mutation := newChannelOverrideTemplateMutation(c.config, OpDelete)
	return &ChannelOverrideTemplateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChannelOverrideTemplateClient) DeleteOne(_m *ChannelOverrideTemplate) *ChannelOverrideTemplateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChannelOverrideTemplateClient) DeleteOneID(id int) *ChannelOverrideTemplateDeleteOne {
	builder := c.Delete().Where(channeloverridetemplate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChannelOverrideTemplateDeleteOne{builder}
}

// Query returns a query builder for ChannelOverrideTemplate.
func (c *ChannelOverrideTemplateClient) Query() *ChannelOverrideTemplateQuery {
	return &ChannelOverrideTemplateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChannelOverrideTemplate},
		inters: c.Interceptors(),
	}
}

// Get returns a ChannelOverrideTemplate entity by its id.
func (c *ChannelOverrideTemplateClient) Get(ctx context.Context, id int) (*ChannelOverrideTemplate, error) {
	return c.Query().Where(channeloverridetemplate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChannelOverrideTemplateClient) GetX(ctx context.Context, id int) *ChannelOverrideTemplate {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ChannelOverrideTemplateClient) Hooks() []Hook {
	hooks := c.hooks.ChannelOverrideTemplate
	return append(hooks[:len(hooks):len(hooks)], channeloverridetemplate.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *ChannelOverrideTemplateClient) Interceptors() []Interceptor {
	inters := c.inters.ChannelOverrideTemplate
	return append(inters[:len(inters):len(inters)], channeloverridetemplate.Interceptors[:]...)
}

func (c *ChannelOverrideTemplateClient) mutate(ctx context.Context, m *ChannelOverrideTemplateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChannelOverrideTemplateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChannelOverrideTemplateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChannelOverrideTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChannelOverrideTemplateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ChannelOverrideTemplate mutation op: %q", m.Op())
	}
}

// ChannelProbeClient is a client for the ChannelProbe schema.
type ChannelProbeClient struct {
	config
}

// NewChannelProbeClient returns a client for the ChannelProbe from the given config.
func NewChannelProbeClient(c config) *ChannelProbeClient {
	return &ChannelProbeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `channelprobe.Hooks(f(g(h())))`.
func (c *ChannelProbeClient) Use(hooks ...Hook) {
	c.hooks.ChannelProbe = append(c.hooks.ChannelProbe, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `channelprobe.Intercept(f(g(h())))`.
func (c *ChannelProbeClient) Intercept(interceptors ...Interceptor) {
	c.inters.ChannelProbe = append(c.inters.ChannelProbe, interceptors...)
}

// Create returns a builder for creating a ChannelProbe entity.
func (c *ChannelProbeClient) Create() *ChannelProbeCreate {
	mutation := newChannelProbeMutation(c.config, OpCreate)
	return &ChannelProbeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ChannelProbe entities.
func (c *ChannelProbeClient) CreateBulk(builders ...*ChannelProbeCreate) *ChannelProbeCreateBulk {
	return &ChannelProbeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChannelProbeClient) MapCreateBulk(slice any, setFunc func(*ChannelProbeCreate, int)) *ChannelProbeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChannelProbeCreateBulk{err: fmt.Errorf("calling to ChannelProbeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChannelProbeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChannelProbeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ChannelProbe.
func (c *ChannelProbeClient) Update() *ChannelProbeUpdate {
	mutation := newChannelProbeMutation(c.config, OpUpdate)
	return &ChannelProbeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChannelProbeClient) UpdateOne(_m *ChannelProbe) *ChannelProbeUpdateOne {
	mutation := newChannelProbeMutation(c.config, OpUpdateOne, withChannelProbe(_m))
	return &ChannelProbeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChannelProbeClient) UpdateOneID(id int) *ChannelProbeUpdateOne {
	mutation := newChannelProbeMutation(c.config, OpUpdateOne, withChannelProbeID(id))
	return &ChannelProbeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ChannelProbe.
func (c *ChannelProbeClient) Delete() *ChannelProbeDelete {
	mutation := newChannelProbeMutation(c.config, OpDelete)
	return &ChannelProbeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChannelProbeClient) DeleteOne(_m *ChannelProbe) *ChannelProbeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChannelProbeClient) DeleteOneID(id int) *ChannelProbeDeleteOne {
	builder := c.Delete().Where(channelprobe.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChannelProbeDeleteOne{builder}
}

// Query returns a query builder for ChannelProbe.
func (c *ChannelProbeClient) Query() *ChannelProbeQuery {
	return &ChannelProbeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChannelProbe},
		inters: c.Interceptors(),
	}
}

// Get returns a ChannelProbe entity by its id.
func (c *ChannelProbeClient) Get(ctx context.Context, id int) (*ChannelProbe, error) {
	return c.Query().Where(channelprobe.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChannelProbeClient) GetX(ctx context.Context, id int) *ChannelProbe {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryChannel queries the channel edge of a ChannelProbe.
func (c *ChannelProbeClient) QueryChannel(_m *ChannelProbe) *ChannelQuery {
	query := (&ChannelClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channelprobe.Table, channelprobe.FieldID, id),
			sqlgraph.To(channel.Table, channel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, channelprobe.ChannelTable, channelprobe.ChannelColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ChannelProbeClient) Hooks() []Hook {
	return c.hooks.ChannelProbe
}

// Interceptors returns the client interceptors.
func (c *ChannelProbeClient) Interceptors() []Interceptor {
	return c.inters.ChannelProbe
}

func (c *ChannelProbeClient) mutate(ctx context.Context, m *ChannelProbeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChannelProbeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChannelProbeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChannelProbeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChannelProbeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ChannelProbe mutation op: %q", m.Op())
	}
}

// ModelClient is a client for the Model schema.
type ModelClient struct {
	config
}

// NewModelClient returns a client for the Model from the given config.
func NewModelClient(c config) *ModelClient {
	return &ModelClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `model.Hooks(f(g(h())))`.
func (c *ModelClient) Use(hooks ...Hook) {
	c.hooks.Model = append(c.hooks.Model, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `model.Intercept(f(g(h())))`.
func (c *ModelClient) Intercept(interceptors ...Interceptor) {
	c.inters.Model = append(c.inters.Model, interceptors...)
}

// Create returns a builder for creating a Model entity.
func (c *ModelClient) Create() *ModelCreate {
	mutation := newModelMutation(c.config, OpCreate)
	return &ModelCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Model entities.
func (c *ModelClient) CreateBulk(builders ...*ModelCreate) *ModelCreateBulk {
	return &ModelCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ModelClient) MapCreateBulk(slice any, setFunc func(*ModelCreate, int)) *ModelCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ModelCreateBulk{err: fmt.Errorf("calling to ModelClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ModelCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ModelCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Model.
func (c *ModelClient) Update() *ModelUpdate {
	mutation := newModelMutation(c.config, OpUpdate)
	return &ModelUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ModelClient) UpdateOne(_m *Model) *ModelUpdateOne {
	mutation := newModelMutation(c.config, OpUpdateOne, withModel(_m))
	return &ModelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ModelClient) UpdateOneID(id int) *ModelUpdateOne {
	mutation := newModelMutation(c.config, OpUpdateOne, withModelID(id))
	return &ModelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Model.
func (c *ModelClient) Delete() *ModelDelete {
	mutation := newModelMutation(c.config, OpDelete)
	return &ModelDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ModelClient) DeleteOne(_m *Model) *ModelDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ModelClient) DeleteOneID(id int) *ModelDeleteOne {
	builder := c.Delete().Where(model.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ModelDeleteOne{builder}
}

// Query returns a query builder for Model.
func (c *ModelClient) Query() *ModelQuery {
	return &ModelQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeModel},
		inters: c.Interceptors(),
	}
}

// Get returns a Model entity by its id.
func (c *ModelClient) Get(ctx context.Context, id int) (*Model, error) {
	return c.Query().Where(model.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ModelClient) GetX(ctx context.Context, id int) *Model {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ModelClient) Hooks() []Hook {
	hooks := c.hooks.Model
	return append(hooks[:len(hooks):len(hooks)], model.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *ModelClient) Interceptors() []Interceptor {
	inters := c.inters.Model
	return append(inters[:len(inters):len(inters)], model.Interceptors[:]...)
}

func (c *ModelClient) mutate(ctx context.Context, m *ModelMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ModelCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ModelUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ModelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ModelDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Model mutation op: %q", m.Op())
	}
}

// ProviderQuotaStatusClient is a client for the ProviderQuotaStatus schema.
type ProviderQuotaStatusClient struct {
	config
}

// NewProviderQuotaStatusClient returns a client for the ProviderQuotaStatus from the given config.
func NewProviderQuotaStatusClient(c config) *ProviderQuotaStatusClient {
	return &ProviderQuotaStatusClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `providerquotastatus.Hooks(f(g(h())))`.
func (c *ProviderQuotaStatusClient) Use(hooks ...Hook) {
	c.hooks.ProviderQuotaStatus = append(c.hooks.ProviderQuotaStatus, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `providerquotastatus.Intercept(f(g(h())))`.
func (c *ProviderQuotaStatusClient) Intercept(interceptors ...Interceptor) {
	c.inters.ProviderQuotaStatus = append(c.inters.ProviderQuotaStatus, interceptors...)
}

// Create returns a builder for creating a ProviderQuotaStatus entity.
func (c *ProviderQuotaStatusClient) Create() *ProviderQuotaStatusCreate {
	mutation := newProviderQuotaStatusMutation(c.config, OpCreate)
	return &ProviderQuotaStatusCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ProviderQuotaStatus entities.
func (c *ProviderQuotaStatusClient) CreateBulk(builders ...*ProviderQuotaStatusCreate) *ProviderQuotaStatusCreateBulk {
	return &ProviderQuotaStatusCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProviderQuotaStatusClient) MapCreateBulk(slice any, setFunc func(*ProviderQuotaStatusCreate, int)) *ProviderQuotaStatusCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProviderQuotaStatusCreateBulk{err: fmt.Errorf("calling to ProviderQuotaStatusClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProviderQuotaStatusCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProviderQuotaStatusCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ProviderQuotaStatus.
func (c *ProviderQuotaStatusClient) Update() *ProviderQuotaStatusUpdate {
	mutation := newProviderQuotaStatusMutation(c.config, OpUpdate)
	return &ProviderQuotaStatusUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProviderQuotaStatusClient) UpdateOne(_m *ProviderQuotaStatus) *ProviderQuotaStatusUpdateOne {
	mutation := newProviderQuotaStatusMutation(c.config, OpUpdateOne, withProviderQuotaStatus(_m))
	return &ProviderQuotaStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProviderQuotaStatusClient) UpdateOneID(id int) *ProviderQuotaStatusUpdateOne {
	mutation := newProviderQuotaStatusMutation(c.config, OpUpdateOne, withProviderQuotaStatusID(id))
	return &ProviderQuotaStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ProviderQuotaStatus.
func (c *ProviderQuotaStatusClient) Delete() *ProviderQuotaStatusDelete {
	mutation := newProviderQuotaStatusMutation(c.config, OpDelete)
	return &ProviderQuotaStatusDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProviderQuotaStatusClient) DeleteOne(_m *ProviderQuotaStatus) *ProviderQuotaStatusDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProviderQuotaStatusClient) DeleteOneID(id int) *ProviderQuotaStatusDeleteOne {
	builder := c.Delete().Where(providerquotastatus.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProviderQuotaStatusDeleteOne{builder}
}

// Query returns a query builder for ProviderQuotaStatus.
func (c *ProviderQuotaStatusClient) Query() *ProviderQuotaStatusQuery {
	return &ProviderQuotaStatusQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProviderQuotaStatus},
		inters: c.Interceptors(),
	}
}

// Get returns a ProviderQuotaStatus entity by its id.
func (c *ProviderQuotaStatusClient) Get(ctx context.Context, id int) (*ProviderQuotaStatus, error) {
	return c.Query().Where(providerquotastatus.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProviderQuotaStatusClient) GetX(ctx context.Context, id int) *ProviderQuotaStatus {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryChannel queries the channel edge of a ProviderQuotaStatus.
func (c *ProviderQuotaStatusClient) QueryChannel(_m *ProviderQuotaStatus) *ChannelQuery {
	query := (&ChannelClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(providerquotastatus.Table, providerquotastatus.FieldID, id),
			sqlgraph.To(channel.Table, channel.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, providerquotastatus.ChannelTable, providerquotastatus.ChannelColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ProviderQuotaStatusClient) Hooks() []Hook {
	hooks := c.hooks.ProviderQuotaStatus
	return append(hooks[:len(hooks):len(hooks)], providerquotastatus.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *ProviderQuotaStatusClient) Interceptors() []Interceptor {
	inters := c.inters.ProviderQuotaStatus
	return append(inters[:len(inters):len(inters)], providerquotastatus.Interceptors[:]...)
}

func (c *ProviderQuotaStatusClient) mutate(ctx context.Context, m *ProviderQuotaStatusMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProviderQuotaStatusCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProviderQuotaStatusUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProviderQuotaStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProviderQuotaStatusDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ProviderQuotaStatus mutation op: %q", m.Op())
	}
}

// RequestClient is a client for the Request schema.
type RequestClient struct {
	config
}

// NewRequestClient returns a client for the Request from the given config.
func NewRequestClient(c config) *RequestClient {
	return &RequestClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `request.Hooks(f(g(h())))`.
func (c *RequestClient) Use(hooks ...Hook) {
	c.hooks.Request = append(c.hooks.Request, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `request.Intercept(f(g(h())))`.
func (c *RequestClient) Intercept(interceptors ...Interceptor) {
	c.inters.Request = append(c.inters.Request, interceptors...)
}

// Create returns a builder for creating a Request entity.
func (c *RequestClient) Create() *RequestCreate {
	mutation := newRequestMutation(c.config, OpCreate)
	return &RequestCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Request entities.
func (c *RequestClient) CreateBulk(builders ...*RequestCreate) *RequestCreateBulk {
	return &RequestCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RequestClient) MapCreateBulk(slice any, setFunc func(*RequestCreate, int)) *RequestCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RequestCreateBulk{err: fmt.Errorf("calling to RequestClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RequestCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RequestCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Request.
func (c *RequestClient) Update() *RequestUpdate {
	mutation := newRequestMutation(c.config, OpUpdate)
	return &RequestUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RequestClient) UpdateOne(_m *Request) *RequestUpdateOne {
	mutation := newRequestMutation(c.config, OpUpdateOne, withRequest(_m))
	return &RequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RequestClient) UpdateOneID(id int) *RequestUpdateOne {
	mutation := newRequestMutation(c.config, OpUpdateOne, withRequestID(id))
	return &RequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Request.
func (c *RequestClient) Delete() *RequestDelete {
	mutation := newRequestMutation(c.config, OpDelete)
	return &RequestDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RequestClient) DeleteOne(_m *Request) *RequestDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RequestClient) DeleteOneID(id int) *RequestDeleteOne {
	builder := c.Delete().Where(request.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RequestDeleteOne{builder}
}

// Query returns a query builder for Request.
func (c *RequestClient) Query() *RequestQuery {
	return &RequestQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRequest},
		inters: c.Interceptors(),
	}
}

// Get returns a Request entity by its id.
func (c *RequestClient) Get(ctx context.Context, id int) (*Request, error) {
	return c.Query().Where(request.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RequestClient) GetX(ctx context.Context, id int) *Request {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAPIKey queries the api_key edge of a Request.
func (c *RequestClient) QueryAPIKey(_m *Request) *APIKeyQuery {
	query := (&APIKeyClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(request.Table, request.FieldID, id),
			sqlgraph.To(apikey.Table, apikey.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, request.APIKeyTable, request.APIKeyColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryExecutions queries the executions edge of a Request.
func (c *RequestClient) QueryExecutions(_m *Request) *RequestExecutionQuery {
	query := (&RequestExecutionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(request.Table, request.FieldID, id),
			sqlgraph.To(requestexecution.Table, requestexecution.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, request.ExecutionsTable, request.ExecutionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChannel queries the channel edge of a Request.
func (c *RequestClient) QueryChannel(_m *Request) *ChannelQuery {
	query := (&ChannelClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(request.Table, request.FieldID, id),
			sqlgraph.To(channel.Table, channel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, request.ChannelTable, request.ChannelColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUsageLogs queries the usage_logs edge of a Request.
func (c *RequestClient) QueryUsageLogs(_m *Request) *UsageLogQuery {
	query := (&UsageLogClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(request.Table, request.FieldID, id),
			sqlgraph.To(usagelog.Table, usagelog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, request.UsageLogsTable, request.UsageLogsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RequestClient) Hooks() []Hook {
	hooks := c.hooks.Request
	return append(hooks[:len(hooks):len(hooks)], request.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *RequestClient) Interceptors() []Interceptor {
	return c.inters.Request
}

func (c *RequestClient) mutate(ctx context.Context, m *RequestMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RequestCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RequestUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RequestDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Request mutation op: %q", m.Op())
	}
}

// RequestExecutionClient is a client for the RequestExecution schema.
type RequestExecutionClient struct {
	config
}

// NewRequestExecutionClient returns a client for the RequestExecution from the given config.
func NewRequestExecutionClient(c config) *RequestExecutionClient {
	return &RequestExecutionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `requestexecution.Hooks(f(g(h())))`.
func (c *RequestExecutionClient) Use(hooks ...Hook) {
	c.hooks.RequestExecution = append(c.hooks.RequestExecution, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `requestexecution.Intercept(f(g(h())))`.
func (c *RequestExecutionClient) Intercept(interceptors ...Interceptor) {
	c.inters.RequestExecution = append(c.inters.RequestExecution, interceptors...)
}

// Create returns a builder for creating a RequestExecution entity.
func (c *RequestExecutionClient) Create() *RequestExecutionCreate {
	mutation := newRequestExecutionMutation(c.config, OpCreate)
	return &RequestExecutionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RequestExecution entities.
func (c *RequestExecutionClient) CreateBulk(builders ...*RequestExecutionCreate) *RequestExecutionCreateBulk {
	return &RequestExecutionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RequestExecutionClient) MapCreateBulk(slice any, setFunc func(*RequestExecutionCreate, int)) *RequestExecutionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RequestExecutionCreateBulk{err: fmt.Errorf("calling to RequestExecutionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RequestExecutionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RequestExecutionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RequestExecution.
func (c *RequestExecutionClient) Update() *RequestExecutionUpdate {
	mutation := newRequestExecutionMutation(c.config, OpUpdate)
	return &RequestExecutionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RequestExecutionClient) UpdateOne(_m *RequestExecution) *RequestExecutionUpdateOne {
	mutation := newRequestExecutionMutation(c.config, OpUpdateOne, withRequestExecution(_m))
	return &RequestExecutionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RequestExecutionClient) UpdateOneID(id int) *RequestExecutionUpdateOne {
	mutation := newRequestExecutionMutation(c.config, OpUpdateOne, withRequestExecutionID(id))
	return &RequestExecutionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RequestExecution.
func (c *RequestExecutionClient) Delete() *RequestExecutionDelete {
	mutation := newRequestExecutionMutation(c.config, OpDelete)
	return &RequestExecutionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RequestExecutionClient) DeleteOne(_m *RequestExecution) *RequestExecutionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RequestExecutionClient) DeleteOneID(id int) *RequestExecutionDeleteOne {
	builder := c.Delete().Where(requestexecution.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RequestExecutionDeleteOne{builder}
}

// Query returns a query builder for RequestExecution.
func (c *RequestExecutionClient) Query() *RequestExecutionQuery {
	return &RequestExecutionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRequestExecution},
		inters: c.Interceptors(),
	}
}

// Get returns a RequestExecution entity by its id.
func (c *RequestExecutionClient) Get(ctx context.Context, id int) (*RequestExecution, error) {
	return c.Query().Where(requestexecution.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RequestExecutionClient) GetX(ctx context.Context, id int) *RequestExecution {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRequest queries the request edge of a RequestExecution.
func (c *RequestExecutionClient) QueryRequest(_m *RequestExecution) *RequestQuery {
	query := (&RequestClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(requestexecution.Table, requestexecution.FieldID, id),
			sqlgraph.To(request.Table, request.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, requestexecution.RequestTable, requestexecution.RequestColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChannel queries the channel edge of a RequestExecution.
func (c *RequestExecutionClient) QueryChannel(_m *RequestExecution) *ChannelQuery {
	query := (&ChannelClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(requestexecution.Table, requestexecution.FieldID, id),
			sqlgraph.To(channel.Table, channel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, requestexecution.ChannelTable, requestexecution.ChannelColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RequestExecutionClient) Hooks() []Hook {
	return c.hooks.RequestExecution
}

// Interceptors returns the client interceptors.
func (c *RequestExecutionClient) Interceptors() []Interceptor {
	return c.inters.RequestExecution
}

func (c *RequestExecutionClient) mutate(ctx context.Context, m *RequestExecutionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RequestExecutionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RequestExecutionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RequestExecutionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RequestExecutionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RequestExecution mutation op: %q", m.Op())
	}
}

// SystemClient is a client for the System schema.
type SystemClient struct {
	config
}

// NewSystemClient returns a client for the System from the given config.
func NewSystemClient(c config) *SystemClient {
	return &SystemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `system.Hooks(f(g(h())))`.
func (c *SystemClient) Use(hooks ...Hook) {
	c.hooks.System = append(c.hooks.System, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `system.Intercept(f(g(h())))`.
func (c *SystemClient) Intercept(interceptors ...Interceptor) {
	c.inters.System = append(c.inters.System, interceptors...)
}

// Create returns a builder for creating a System entity.
func (c *SystemClient) Create() *SystemCreate {
	mutation := newSystemMutation(c.config, OpCreate)
	return &SystemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of System entities.
func (c *SystemClient) CreateBulk(builders ...*SystemCreate) *SystemCreateBulk {
	return &SystemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SystemClient) MapCreateBulk(slice any, setFunc func(*SystemCreate, int)) *SystemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SystemCreateBulk{err: fmt.Errorf("calling to SystemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SystemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SystemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for System.
func (c *SystemClient) Update() *SystemUpdate {
	mutation := newSystemMutation(c.config, OpUpdate)
	return &SystemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SystemClient) UpdateOne(_m *System) *SystemUpdateOne {
	mutation := newSystemMutation(c.config, OpUpdateOne, withSystem(_m))
	return &SystemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SystemClient) UpdateOneID(id int) *SystemUpdateOne {
	mutation := newSystemMutation(c.config, OpUpdateOne, withSystemID(id))
	return &SystemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for System.
func (c *SystemClient) Delete() *SystemDelete {
	mutation := newSystemMutation(c.config, OpDelete)
	return &SystemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SystemClient) DeleteOne(_m *System) *SystemDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SystemClient) DeleteOneID(id int) *SystemDeleteOne {
	builder := c.Delete().Where(system.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SystemDeleteOne{builder}
}

// Query returns a query builder for System.
func (c *SystemClient) Query() *SystemQuery {
	return &SystemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSystem},
		inters: c.Interceptors(),
	}
}

// Get returns a System entity by its id.
func (c *SystemClient) Get(ctx context.Context, id int) (*System, error) {
	return c.Query().Where(system.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SystemClient) GetX(ctx context.Context, id int) *System {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SystemClient) Hooks() []Hook {
	hooks := c.hooks.System
	return append(hooks[:len(hooks):len(hooks)], system.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *SystemClient) Interceptors() []Interceptor {
	inters := c.inters.System
	return append(inters[:len(inters):len(inters)], system.Interceptors[:]...)
}

func (c *SystemClient) mutate(ctx context.Context, m *SystemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SystemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SystemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SystemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SystemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown System mutation op: %q", m.Op())
	}
}

// UsageLogClient is a client for the UsageLog schema.
type UsageLogClient struct {
	config
}

// NewUsageLogClient returns a client for the UsageLog from the given config.
func NewUsageLogClient(c config) *UsageLogClient {
	return &UsageLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `usagelog.Hooks(f(g(h())))`.
func (c *UsageLogClient) Use(hooks ...Hook) {
	c.hooks.UsageLog = append(c.hooks.UsageLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `usagelog.Intercept(f(g(h())))`.
func (c *UsageLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.UsageLog = append(c.inters.UsageLog, interceptors...)
}

// Create returns a builder for creating a UsageLog entity.
func (c *UsageLogClient) Create() *UsageLogCreate {
	mutation := newUsageLogMutation(c.config, OpCreate)
	return &UsageLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UsageLog entities.
func (c *UsageLogClient) CreateBulk(builders ...*UsageLogCreate) *UsageLogCreateBulk {
	return &UsageLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UsageLogClient) MapCreateBulk(slice any, setFunc func(*UsageLogCreate, int)) *UsageLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UsageLogCreateBulk{err: fmt.Errorf("calling to UsageLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UsageLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UsageLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UsageLog.
func (c *UsageLogClient) Update() *UsageLogUpdate {
	mutation := newUsageLogMutation(c.config, OpUpdate)
	return &UsageLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UsageLogClient) UpdateOne(_m *UsageLog) *UsageLogUpdateOne {
	mutation := newUsageLogMutation(c.config, OpUpdateOne, withUsageLog(_m))
	return &UsageLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UsageLogClient) UpdateOneID(id int) *UsageLogUpdateOne {
	mutation := newUsageLogMutation(c.config, OpUpdateOne, withUsageLogID(id))
	return &UsageLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UsageLog.
func (c *UsageLogClient) Delete() *UsageLogDelete {
	mutation := newUsageLogMutation(c.config, OpDelete)
	return &UsageLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UsageLogClient) DeleteOne(_m *UsageLog) *UsageLogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UsageLogClient) DeleteOneID(id int) *UsageLogDeleteOne {
	builder := c.Delete().Where(usagelog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UsageLogDeleteOne{builder}
}

// Query returns a query builder for UsageLog.
func (c *UsageLogClient) Query() *UsageLogQuery {
	return &UsageLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUsageLog},
		inters: c.Interceptors(),
	}
}

// Get returns a UsageLog entity by its id.
func (c *UsageLogClient) Get(ctx context.Context, id int) (*UsageLog, error) {
	return c.Query().Where(usagelog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UsageLogClient) GetX(ctx context.Context, id int) *UsageLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRequest queries the request edge of a UsageLog.
func (c *UsageLogClient) QueryRequest(_m *UsageLog) *RequestQuery {
	query := (&RequestClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(usagelog.Table, usagelog.FieldID, id),
			sqlgraph.To(request.Table, request.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, usagelog.RequestTable, usagelog.RequestColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChannel queries the channel edge of a UsageLog.
func (c *UsageLogClient) QueryChannel(_m *UsageLog) *ChannelQuery {
	query := (&ChannelClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(usagelog.Table, usagelog.FieldID, id),
			sqlgraph.To(channel.Table, channel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, usagelog.ChannelTable, usagelog.ChannelColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UsageLogClient) Hooks() []Hook {
	hooks := c.hooks.UsageLog
	return append(hooks[:len(hooks):len(hooks)], usagelog.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *UsageLogClient) Interceptors() []Interceptor {
	return c.inters.UsageLog
}

func (c *UsageLogClient) mutate(ctx context.Context, m *UsageLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UsageLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UsageLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UsageLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UsageLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UsageLog mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	hooks := c.hooks.User
	return append(hooks[:len(hooks):len(hooks)], user.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	inters := c.inters.User
	return append(inters[:len(inters):len(inters)], user.Interceptors[:]...)
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		APIKey, Channel, ChannelModelPrice, ChannelModelPriceVersion,
		ChannelOverrideTemplate, ChannelProbe, Model, ProviderQuotaStatus, Request,
		RequestExecution, System, UsageLog, User []ent.Hook
	}
	inters struct {
		APIKey, Channel, ChannelModelPrice, ChannelModelPriceVersion,
		ChannelOverrideTemplate, ChannelProbe, Model, ProviderQuotaStatus, Request,
		RequestExecution, System, UsageLog, User []ent.Interceptor
	}
)
