// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/model"
	"github.com/looplj/axonhub/internal/ent/request"
	"github.com/looplj/axonhub/internal/ent/usagelog"
	"github.com/looplj/axonhub/internal/objects"
)

// CreateAPIKeyInput represents a mutation input for creating apikeys.
type CreateAPIKeyInput struct {
	Name string
}

// Mutate applies the CreateAPIKeyInput on the APIKeyMutation builder.
func (i *CreateAPIKeyInput) Mutate(m *APIKeyMutation) {
	m.SetName(i.Name)
}

// SetInput applies the change-set in the CreateAPIKeyInput on the APIKeyCreate builder.
func (c *APIKeyCreate) SetInput(i CreateAPIKeyInput) *APIKeyCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateAPIKeyInput represents a mutation input for updating apikeys.
type UpdateAPIKeyInput struct {
	Name *string
}

// Mutate applies the UpdateAPIKeyInput on the APIKeyMutation builder.
func (i *UpdateAPIKeyInput) Mutate(m *APIKeyMutation) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
}

// SetInput applies the change-set in the UpdateAPIKeyInput on the APIKeyUpdate builder.
func (c *APIKeyUpdate) SetInput(i UpdateAPIKeyInput) *APIKeyUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateAPIKeyInput on the APIKeyUpdateOne builder.
func (c *APIKeyUpdateOne) SetInput(i UpdateAPIKeyInput) *APIKeyUpdateOne {
	i.Mutate(c.Mutation())
	return c
}

// CreateChannelInput represents a mutation input for creating channels.
type CreateChannelInput struct {
	Type                    channel.Type
	BaseURL                 *string
	Name                    string
	Credentials             objects.ChannelCredentials
	SupportedModels         []string
	ManualModels            []string
	AutoSyncSupportedModels *bool
	AutoSyncModelPattern    *string
	Tags                    []string
	DefaultTestModel        string
	Policies                *objects.ChannelPolicies
	Settings                *objects.ChannelSettings
	OrderingWeight          *int
	Remark                  *string
	Endpoints               []objects.ChannelEndpoint
}

// Mutate applies the CreateChannelInput on the ChannelMutation builder.
func (i *CreateChannelInput) Mutate(m *ChannelMutation) {
	m.SetType(i.Type)
	if v := i.BaseURL; v != nil {
		m.SetBaseURL(*v)
	}
	m.SetName(i.Name)
	m.SetCredentials(i.Credentials)
	if v := i.SupportedModels; v != nil {
		m.SetSupportedModels(v)
	}
	if v := i.ManualModels; v != nil {
		m.SetManualModels(v)
	}
	if v := i.AutoSyncSupportedModels; v != nil {
		m.SetAutoSyncSupportedModels(*v)
	}
	if v := i.AutoSyncModelPattern; v != nil {
		m.SetAutoSyncModelPattern(*v)
	}
	if v := i.Tags; v != nil {
		m.SetTags(v)
	}
	m.SetDefaultTestModel(i.DefaultTestModel)
	if v := i.Policies; v != nil {
		m.SetPolicies(*v)
	}
	if v := i.Settings; v != nil {
		m.SetSettings(v)
	}
	if v := i.OrderingWeight; v != nil {
		m.SetOrderingWeight(*v)
	}
	if v := i.Remark; v != nil {
		m.SetRemark(*v)
	}
	if v := i.Endpoints; v != nil {
		m.SetEndpoints(v)
	}
}

// SetInput applies the change-set in the CreateChannelInput on the ChannelCreate builder.
func (c *ChannelCreate) SetInput(i CreateChannelInput) *ChannelCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateChannelInput represents a mutation input for updating channels.
type UpdateChannelInput struct {
	Type                      *channel.Type
	ClearBaseURL              bool
	BaseURL                   *string
	Name                      *string
	Status                    *channel.Status
	Credentials               *objects.ChannelCredentials
	SupportedModels           []string
	AppendSupportedModels     []string
	ClearManualModels         bool
	ManualModels              []string
	AppendManualModels        []string
	AutoSyncSupportedModels   *bool
	ClearAutoSyncModelPattern bool
	AutoSyncModelPattern      *string
	ClearTags                 bool
	Tags                      []string
	AppendTags                []string
	DefaultTestModel          *string
	ClearPolicies             bool
	Policies                  *objects.ChannelPolicies
	ClearSettings             bool
	Settings                  *objects.ChannelSettings
	OrderingWeight            *int
	ClearErrorMessage         bool
	ErrorMessage              *string
	ClearRemark               bool
	Remark                    *string
	ClearEndpoints            bool
	Endpoints                 []objects.ChannelEndpoint
	AppendEndpoints           []objects.ChannelEndpoint
}

// Mutate applies the UpdateChannelInput on the ChannelMutation builder.
func (i *UpdateChannelInput) Mutate(m *ChannelMutation) {
	if v := i.Type; v != nil {
		m.SetType(*v)
	}
	if i.ClearBaseURL {
		m.ClearBaseURL()
	}
	if v := i.BaseURL; v != nil {
		m.SetBaseURL(*v)
	}
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if v := i.Credentials; v != nil {
		m.SetCredentials(*v)
	}
	if v := i.SupportedModels; v != nil {
		m.SetSupportedModels(v)
	}
	if i.AppendSupportedModels != nil {
		m.AppendSupportedModels(i.SupportedModels)
	}
	if i.ClearManualModels {
		m.ClearManualModels()
	}
	if v := i.ManualModels; v != nil {
		m.SetManualModels(v)
	}
	if i.AppendManualModels != nil {
		m.AppendManualModels(i.ManualModels)
	}
	if v := i.AutoSyncSupportedModels; v != nil {
		m.SetAutoSyncSupportedModels(*v)
	}
	if i.ClearAutoSyncModelPattern {
		m.ClearAutoSyncModelPattern()
	}
	if v := i.AutoSyncModelPattern; v != nil {
		m.SetAutoSyncModelPattern(*v)
	}
	if i.ClearTags {
		m.ClearTags()
	}
	if v := i.Tags; v != nil {
		m.SetTags(v)
	}
	if i.AppendTags != nil {
		m.AppendTags(i.Tags)
	}
	if v := i.DefaultTestModel; v != nil {
		m.SetDefaultTestModel(*v)
	}
	if i.ClearPolicies {
		m.ClearPolicies()
	}
	if v := i.Policies; v != nil {
		m.SetPolicies(*v)
	}
	if i.ClearSettings {
		m.ClearSettings()
	}
	if v := i.Settings; v != nil {
		m.SetSettings(v)
	}
	if v := i.OrderingWeight; v != nil {
		m.SetOrderingWeight(*v)
	}
	if i.ClearErrorMessage {
		m.ClearErrorMessage()
	}
	if v := i.ErrorMessage; v != nil {
		m.SetErrorMessage(*v)
	}
	if i.ClearRemark {
		m.ClearRemark()
	}
	if v := i.Remark; v != nil {
		m.SetRemark(*v)
	}
	if i.ClearEndpoints {
		m.ClearEndpoints()
	}
	if v := i.Endpoints; v != nil {
		m.SetEndpoints(v)
	}
	if i.AppendEndpoints != nil {
		m.AppendEndpoints(i.Endpoints)
	}
}

// SetInput applies the change-set in the UpdateChannelInput on the ChannelUpdate builder.
func (c *ChannelUpdate) SetInput(i UpdateChannelInput) *ChannelUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateChannelInput on the ChannelUpdateOne builder.
func (c *ChannelUpdateOne) SetInput(i UpdateChannelInput) *ChannelUpdateOne {
	i.Mutate(c.Mutation())
	return c
}

// CreateChannelOverrideTemplateInput represents a mutation input for creating channeloverridetemplates.
type CreateChannelOverrideTemplateInput struct {
	Name                     string
	Description              *string
	HeaderOverrideOperations []objects.OverrideOperation
	BodyOverrideOperations   []objects.OverrideOperation
}

// Mutate applies the CreateChannelOverrideTemplateInput on the ChannelOverrideTemplateMutation builder.
func (i *CreateChannelOverrideTemplateInput) Mutate(m *ChannelOverrideTemplateMutation) {
	m.SetName(i.Name)
	if v := i.Description; v != nil {
		m.SetDescription(*v)
	}
	if v := i.HeaderOverrideOperations; v != nil {
		m.SetHeaderOverrideOperations(v)
	}
	if v := i.BodyOverrideOperations; v != nil {
		m.SetBodyOverrideOperations(v)
	}
}

// SetInput applies the change-set in the CreateChannelOverrideTemplateInput on the ChannelOverrideTemplateCreate builder.
func (c *ChannelOverrideTemplateCreate) SetInput(i CreateChannelOverrideTemplateInput) *ChannelOverrideTemplateCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateChannelOverrideTemplateInput represents a mutation input for updating channeloverridetemplates.
type UpdateChannelOverrideTemplateInput struct {
	Name                           *string
	ClearDescription               bool
	Description                    *string
	ClearHeaderOverrideOperations  bool
	HeaderOverrideOperations       []objects.OverrideOperation
	AppendHeaderOverrideOperations []objects.OverrideOperation
	ClearBodyOverrideOperations    bool
	BodyOverrideOperations         []objects.OverrideOperation
	AppendBodyOverrideOperations   []objects.OverrideOperation
}

// Mutate applies the UpdateChannelOverrideTemplateInput on the ChannelOverrideTemplateMutation builder.
func (i *UpdateChannelOverrideTemplateInput) Mutate(m *ChannelOverrideTemplateMutation) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if i.ClearDescription {
		m.ClearDescription()
	}
	if v := i.Description; v != nil {
		m.SetDescription(*v)
	}
	if i.ClearHeaderOverrideOperations {
		m.ClearHeaderOverrideOperations()
	}
	if v := i.HeaderOverrideOperations; v != nil {
		m.SetHeaderOverrideOperations(v)
	}
	if i.AppendHeaderOverrideOperations != nil {
		m.AppendHeaderOverrideOperations(i.HeaderOverrideOperations)
	}
	if i.ClearBodyOverrideOperations {
		m.ClearBodyOverrideOperations()
	}
	if v := i.BodyOverrideOperations; v != nil {
		m.SetBodyOverrideOperations(v)
	}
	if i.AppendBodyOverrideOperations != nil {
		m.AppendBodyOverrideOperations(i.BodyOverrideOperations)
	}
}

// SetInput applies the change-set in the UpdateChannelOverrideTemplateInput on the ChannelOverrideTemplateUpdate builder.
func (c *ChannelOverrideTemplateUpdate) SetInput(i UpdateChannelOverrideTemplateInput) *ChannelOverrideTemplateUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateChannelOverrideTemplateInput on the ChannelOverrideTemplateUpdateOne builder.
func (c *ChannelOverrideTemplateUpdateOne) SetInput(i UpdateChannelOverrideTemplateInput) *ChannelOverrideTemplateUpdateOne {
	i.Mutate(c.Mutation())
	return c
}

// CreateModelInput represents a mutation input for creating models.
type CreateModelInput struct {
	Developer string
	ModelID   string
	Type      *model.Type
	Name      string
	Icon      string
	Group     string
	ModelCard *objects.ModelCard
	Settings  *objects.ModelSettings
	Remark    *string
}

// Mutate applies the CreateModelInput on the ModelMutation builder.
func (i *CreateModelInput) Mutate(m *ModelMutation) {
	m.SetDeveloper(i.Developer)
	m.SetModelID(i.ModelID)
	if v := i.Type; v != nil {
		m.SetType(*v)
	}
	m.SetName(i.Name)
	m.SetIcon(i.Icon)
	m.SetGroup(i.Group)
	if v := i.ModelCard; v != nil {
		m.SetModelCard(v)
	}
	if v := i.Settings; v != nil {
		m.SetSettings(v)
	}
	if v := i.Remark; v != nil {
		m.SetRemark(*v)
	}
}

// SetInput applies the change-set in the CreateModelInput on the ModelCreate builder.
func (c *ModelCreate) SetInput(i CreateModelInput) *ModelCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateModelInput represents a mutation input for updating models.
type UpdateModelInput struct {
	Developer   *string
	ModelID     *string
	Type        *model.Type
	Name        *string
	Icon        *string
	Group       *string
	ModelCard   *objects.ModelCard
	Settings    *objects.ModelSettings
	Status      *model.Status
	ClearRemark bool
	Remark      *string
}

// Mutate applies the UpdateModelInput on the ModelMutation builder.
func (i *UpdateModelInput) Mutate(m *ModelMutation) {
	if v := i.Developer; v != nil {
		m.SetDeveloper(*v)
	}
	if v := i.ModelID; v != nil {
		m.SetModelID(*v)
	}
	if v := i.Type; v != nil {
		m.SetType(*v)
	}
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if v := i.Icon; v != nil {
		m.SetIcon(*v)
	}
	if v := i.Group; v != nil {
		m.SetGroup(*v)
	}
	if v := i.ModelCard; v != nil {
		m.SetModelCard(v)
	}
	if v := i.Settings; v != nil {
		m.SetSettings(v)
	}
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if i.ClearRemark {
		m.ClearRemark()
	}
	if v := i.Remark; v != nil {
		m.SetRemark(*v)
	}
}

// SetInput applies the change-set in the UpdateModelInput on the ModelUpdate builder.
func (c *ModelUpdate) SetInput(i UpdateModelInput) *ModelUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateModelInput on the ModelUpdateOne builder.
func (c *ModelUpdateOne) SetInput(i UpdateModelInput) *ModelUpdateOne {
	i.Mutate(c.Mutation())
	return c
}

// CreateRequestInput represents a mutation input for creating requests.
type CreateRequestInput struct {
	Source                     *request.Source
	ModelID                    string
	ReasoningEffort            *string
	Format                     *string
	RequestHeaders             objects.JSONRawMessage
	RequestBody                objects.JSONRawMessage
	ResponseBody               objects.JSONRawMessage
	ResponseChunks             []objects.JSONRawMessage
	ExternalID                 *string
	Status                     request.Status
	Stream                     *bool
	ClientIP                   *string
	MetricsLatencyMs           *int64
	MetricsFirstTokenLatencyMs *int64
	MetricsReasoningDurationMs *int64
	APIKeyID                   *int
	TraceID                    *int
	ChannelID                  *int
}

// Mutate applies the CreateRequestInput on the RequestMutation builder.
func (i *CreateRequestInput) Mutate(m *RequestMutation) {
	if v := i.Source; v != nil {
		m.SetSource(*v)
	}
	m.SetModelID(i.ModelID)
	if v := i.ReasoningEffort; v != nil {
		m.SetReasoningEffort(*v)
	}
	if v := i.Format; v != nil {
		m.SetFormat(*v)
	}
	if v := i.RequestHeaders; v != nil {
		m.SetRequestHeaders(v)
	}
	if v := i.RequestBody; v != nil {
		m.SetRequestBody(v)
	}
	if v := i.ResponseBody; v != nil {
		m.SetResponseBody(v)
	}
	if v := i.ResponseChunks; v != nil {
		m.SetResponseChunks(v)
	}
	if v := i.ExternalID; v != nil {
		m.SetExternalID(*v)
	}
	m.SetStatus(i.Status)
	if v := i.Stream; v != nil {
		m.SetStream(*v)
	}
	if v := i.ClientIP; v != nil {
		m.SetClientIP(*v)
	}
	if v := i.MetricsLatencyMs; v != nil {
		m.SetMetricsLatencyMs(*v)
	}
	if v := i.MetricsFirstTokenLatencyMs; v != nil {
		m.SetMetricsFirstTokenLatencyMs(*v)
	}
	if v := i.MetricsReasoningDurationMs; v != nil {
		m.SetMetricsReasoningDurationMs(*v)
	}
	if v := i.APIKeyID; v != nil {
		m.SetAPIKeyID(*v)
	}
	if v := i.TraceID; v != nil {
		m.SetTraceID(*v)
	}
	if v := i.ChannelID; v != nil {
		m.SetChannelID(*v)
	}
}

// SetInput applies the change-set in the CreateRequestInput on the RequestCreate builder.
func (c *RequestCreate) SetInput(i CreateRequestInput) *RequestCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateRequestInput represents a mutation input for updating requests.
type UpdateRequestInput struct {
	ClearRequestHeaders             bool
	RequestHeaders                  objects.JSONRawMessage
	AppendRequestHeaders            objects.JSONRawMessage
	ClearResponseBody               bool
	ResponseBody                    objects.JSONRawMessage
	AppendResponseBody              objects.JSONRawMessage
	ClearResponseChunks             bool
	ResponseChunks                  []objects.JSONRawMessage
	AppendResponseChunks            []objects.JSONRawMessage
	ClearExternalID                 bool
	ExternalID                      *string
	Status                          *request.Status
	ClearMetricsLatencyMs           bool
	MetricsLatencyMs                *int64
	ClearMetricsFirstTokenLatencyMs bool
	MetricsFirstTokenLatencyMs      *int64
	ClearMetricsReasoningDurationMs bool
	MetricsReasoningDurationMs      *int64
	ClearChannel                    bool
	ChannelID                       *int
}

// Mutate applies the UpdateRequestInput on the RequestMutation builder.
func (i *UpdateRequestInput) Mutate(m *RequestMutation) {
	if i.ClearRequestHeaders {
		m.ClearRequestHeaders()
	}
	if v := i.RequestHeaders; v != nil {
		m.SetRequestHeaders(v)
	}
	if i.AppendRequestHeaders != nil {
		m.AppendRequestHeaders(i.RequestHeaders)
	}
	if i.ClearResponseBody {
		m.ClearResponseBody()
	}
	if v := i.ResponseBody; v != nil {
		m.SetResponseBody(v)
	}
	if i.AppendResponseBody != nil {
		m.AppendResponseBody(i.ResponseBody)
	}
	if i.ClearResponseChunks {
		m.ClearResponseChunks()
	}
	if v := i.ResponseChunks; v != nil {
		m.SetResponseChunks(v)
	}
	if i.AppendResponseChunks != nil {
		m.AppendResponseChunks(i.ResponseChunks)
	}
	if i.ClearExternalID {
		m.ClearExternalID()
	}
	if v := i.ExternalID; v != nil {
		m.SetExternalID(*v)
	}
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if i.ClearMetricsLatencyMs {
		m.ClearMetricsLatencyMs()
	}
	if v := i.MetricsLatencyMs; v != nil {
		m.SetMetricsLatencyMs(*v)
	}
	if i.ClearMetricsFirstTokenLatencyMs {
		m.ClearMetricsFirstTokenLatencyMs()
	}
	if v := i.MetricsFirstTokenLatencyMs; v != nil {
		m.SetMetricsFirstTokenLatencyMs(*v)
	}
	if i.ClearMetricsReasoningDurationMs {
		m.ClearMetricsReasoningDurationMs()
	}
	if v := i.MetricsReasoningDurationMs; v != nil {
		m.SetMetricsReasoningDurationMs(*v)
	}
	if i.ClearChannel {
		m.ClearChannel()
	}
	if v := i.ChannelID; v != nil {
		m.SetChannelID(*v)
	}
}

// SetInput applies the change-set in the UpdateRequestInput on the RequestUpdate builder.
func (c *RequestUpdate) SetInput(i UpdateRequestInput) *RequestUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateRequestInput on the RequestUpdateOne builder.
func (c *RequestUpdateOne) SetInput(i UpdateRequestInput) *RequestUpdateOne {
	i.Mutate(c.Mutation())
	return c
}

// CreateSystemInput represents a mutation input for creating systems.
type CreateSystemInput struct {
	Key   string
	Value string
}

// Mutate applies the CreateSystemInput on the SystemMutation builder.
func (i *CreateSystemInput) Mutate(m *SystemMutation) {
	m.SetKey(i.Key)
	m.SetValue(i.Value)
}

// SetInput applies the change-set in the CreateSystemInput on the SystemCreate builder.
func (c *SystemCreate) SetInput(i CreateSystemInput) *SystemCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateSystemInput represents a mutation input for updating systems.
type UpdateSystemInput struct {
	Key   *string
	Value *string
}

// Mutate applies the UpdateSystemInput on the SystemMutation builder.
func (i *UpdateSystemInput) Mutate(m *SystemMutation) {
	if v := i.Key; v != nil {
		m.SetKey(*v)
	}
	if v := i.Value; v != nil {
		m.SetValue(*v)
	}
}

// SetInput applies the change-set in the UpdateSystemInput on the SystemUpdate builder.
func (c *SystemUpdate) SetInput(i UpdateSystemInput) *SystemUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateSystemInput on the SystemUpdateOne builder.
func (c *SystemUpdateOne) SetInput(i UpdateSystemInput) *SystemUpdateOne {
	i.Mutate(c.Mutation())
	return c
}

// CreateThreadInput represents a mutation input for creating threads.
type CreateThreadInput struct {
	ThreadID string
}

// Mutate applies the CreateThreadInput on the ThreadMutation builder.
func (i *CreateThreadInput) Mutate(m *ThreadMutation) {
	m.SetThreadID(i.ThreadID)
}

// SetInput applies the change-set in the CreateThreadInput on the ThreadCreate builder.
func (c *ThreadCreate) SetInput(i CreateThreadInput) *ThreadCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateThreadInput represents a mutation input for updating threads.
type UpdateThreadInput struct {
	ThreadID *string
}

// Mutate applies the UpdateThreadInput on the ThreadMutation builder.
func (i *UpdateThreadInput) Mutate(m *ThreadMutation) {
	if v := i.ThreadID; v != nil {
		m.SetThreadID(*v)
	}
}

// SetInput applies the change-set in the UpdateThreadInput on the ThreadUpdate builder.
func (c *ThreadUpdate) SetInput(i UpdateThreadInput) *ThreadUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateThreadInput on the ThreadUpdateOne builder.
func (c *ThreadUpdateOne) SetInput(i UpdateThreadInput) *ThreadUpdateOne {
	i.Mutate(c.Mutation())
	return c
}

// CreateTraceInput represents a mutation input for creating traces.
type CreateTraceInput struct {
	TraceID  string
	ThreadID *int
}

// Mutate applies the CreateTraceInput on the TraceMutation builder.
func (i *CreateTraceInput) Mutate(m *TraceMutation) {
	m.SetTraceID(i.TraceID)
	if v := i.ThreadID; v != nil {
		m.SetThreadID(*v)
	}
}

// SetInput applies the change-set in the CreateTraceInput on the TraceCreate builder.
func (c *TraceCreate) SetInput(i CreateTraceInput) *TraceCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateTraceInput represents a mutation input for updating traces.
type UpdateTraceInput struct {
	TraceID *string
}

// Mutate applies the UpdateTraceInput on the TraceMutation builder.
func (i *UpdateTraceInput) Mutate(m *TraceMutation) {
	if v := i.TraceID; v != nil {
		m.SetTraceID(*v)
	}
}

// SetInput applies the change-set in the UpdateTraceInput on the TraceUpdate builder.
func (c *TraceUpdate) SetInput(i UpdateTraceInput) *TraceUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateTraceInput on the TraceUpdateOne builder.
func (c *TraceUpdateOne) SetInput(i UpdateTraceInput) *TraceUpdateOne {
	i.Mutate(c.Mutation())
	return c
}

// CreateUsageLogInput represents a mutation input for creating usagelogs.
type CreateUsageLogInput struct {
	APIKeyID                           *int
	ModelID                            string
	PromptTokens                       *int64
	CompletionTokens                   *int64
	TotalTokens                        *int64
	PromptAudioTokens                  *int64
	PromptCachedTokens                 *int64
	PromptWriteCachedTokens            *int64
	PromptWriteCachedTokens5m          *int64
	PromptWriteCachedTokens1h          *int64
	CompletionAudioTokens              *int64
	CompletionReasoningTokens          *int64
	CompletionAcceptedPredictionTokens *int64
	CompletionRejectedPredictionTokens *int64
	Source                             *usagelog.Source
	Format                             *string
	TotalCost                          *float64
	CostItems                          []objects.CostItem
	CostPriceReferenceID               *string
	RequestID                          int
	ChannelID                          *int
}

// Mutate applies the CreateUsageLogInput on the UsageLogMutation builder.
func (i *CreateUsageLogInput) Mutate(m *UsageLogMutation) {
	if v := i.APIKeyID; v != nil {
		m.SetAPIKeyID(*v)
	}
	m.SetModelID(i.ModelID)
	if v := i.PromptTokens; v != nil {
		m.SetPromptTokens(*v)
	}
	if v := i.CompletionTokens; v != nil {
		m.SetCompletionTokens(*v)
	}
	if v := i.TotalTokens; v != nil {
		m.SetTotalTokens(*v)
	}
	if v := i.PromptAudioTokens; v != nil {
		m.SetPromptAudioTokens(*v)
	}
	if v := i.PromptCachedTokens; v != nil {
		m.SetPromptCachedTokens(*v)
	}
	if v := i.PromptWriteCachedTokens; v != nil {
		m.SetPromptWriteCachedTokens(*v)
	}
	if v := i.PromptWriteCachedTokens5m; v != nil {
		m.SetPromptWriteCachedTokens5m(*v)
	}
	if v := i.PromptWriteCachedTokens1h; v != nil {
		m.SetPromptWriteCachedTokens1h(*v)
	}
	if v := i.CompletionAudioTokens; v != nil {
		m.SetCompletionAudioTokens(*v)
	}
	if v := i.CompletionReasoningTokens; v != nil {
		m.SetCompletionReasoningTokens(*v)
	}
	if v := i.CompletionAcceptedPredictionTokens; v != nil {
		m.SetCompletionAcceptedPredictionTokens(*v)
	}
	if v := i.CompletionRejectedPredictionTokens; v != nil {
		m.SetCompletionRejectedPredictionTokens(*v)
	}
	if v := i.Source; v != nil {
		m.SetSource(*v)
	}
	if v := i.Format; v != nil {
		m.SetFormat(*v)
	}
	if v := i.TotalCost; v != nil {
		m.SetTotalCost(*v)
	}
	if v := i.CostItems; v != nil {
		m.SetCostItems(v)
	}
	if v := i.CostPriceReferenceID; v != nil {
		m.SetCostPriceReferenceID(*v)
	}
	m.SetRequestID(i.RequestID)
	if v := i.ChannelID; v != nil {
		m.SetChannelID(*v)
	}
}

// SetInput applies the change-set in the CreateUsageLogInput on the UsageLogCreate builder.
func (c *UsageLogCreate) SetInput(i CreateUsageLogInput) *UsageLogCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateUsageLogInput represents a mutation input for updating usagelogs.
type UpdateUsageLogInput struct {
	PromptTokens                            *int64
	CompletionTokens                        *int64
	TotalTokens                             *int64
	ClearPromptAudioTokens                  bool
	PromptAudioTokens                       *int64
	ClearPromptCachedTokens                 bool
	PromptCachedTokens                      *int64
	ClearPromptWriteCachedTokens            bool
	PromptWriteCachedTokens                 *int64
	ClearPromptWriteCachedTokens5m          bool
	PromptWriteCachedTokens5m               *int64
	ClearPromptWriteCachedTokens1h          bool
	PromptWriteCachedTokens1h               *int64
	ClearCompletionAudioTokens              bool
	CompletionAudioTokens                   *int64
	ClearCompletionReasoningTokens          bool
	CompletionReasoningTokens               *int64
	ClearCompletionAcceptedPredictionTokens bool
	CompletionAcceptedPredictionTokens      *int64
	ClearCompletionRejectedPredictionTokens bool
	CompletionRejectedPredictionTokens      *int64
	ClearTotalCost                          bool
	TotalCost                               *float64
	ClearCostItems                          bool
	CostItems                               []objects.CostItem
	AppendCostItems                         []objects.CostItem
	ClearCostPriceReferenceID               bool
	CostPriceReferenceID                    *string
}

// Mutate applies the UpdateUsageLogInput on the UsageLogMutation builder.
func (i *UpdateUsageLogInput) Mutate(m *UsageLogMutation) {
	if v := i.PromptTokens; v != nil {
		m.SetPromptTokens(*v)
	}
	if v := i.CompletionTokens; v != nil {
		m.SetCompletionTokens(*v)
	}
	if v := i.TotalTokens; v != nil {
		m.SetTotalTokens(*v)
	}
	if i.ClearPromptAudioTokens {
		m.ClearPromptAudioTokens()
	}
	if v := i.PromptAudioTokens; v != nil {
		m.SetPromptAudioTokens(*v)
	}
	if i.ClearPromptCachedTokens {
		m.ClearPromptCachedTokens()
	}
	if v := i.PromptCachedTokens; v != nil {
		m.SetPromptCachedTokens(*v)
	}
	if i.ClearPromptWriteCachedTokens {
		m.ClearPromptWriteCachedTokens()
	}
	if v := i.PromptWriteCachedTokens; v != nil {
		m.SetPromptWriteCachedTokens(*v)
	}
	if i.ClearPromptWriteCachedTokens5m {
		m.ClearPromptWriteCachedTokens5m()
	}
	if v := i.PromptWriteCachedTokens5m; v != nil {
		m.SetPromptWriteCachedTokens5m(*v)
	}
	if i.ClearPromptWriteCachedTokens1h {
		m.ClearPromptWriteCachedTokens1h()
	}
	if v := i.PromptWriteCachedTokens1h; v != nil {
		m.SetPromptWriteCachedTokens1h(*v)
	}
	if i.ClearCompletionAudioTokens {
		m.ClearCompletionAudioTokens()
	}
	if v := i.CompletionAudioTokens; v != nil {
		m.SetCompletionAudioTokens(*v)
	}
	if i.ClearCompletionReasoningTokens {
		m.ClearCompletionReasoningTokens()
	}
	if v := i.CompletionReasoningTokens; v != nil {
		m.SetCompletionReasoningTokens(*v)
	}
	if i.ClearCompletionAcceptedPredictionTokens {
		m.ClearCompletionAcceptedPredictionTokens()
	}
	if v := i.CompletionAcceptedPredictionTokens; v != nil {
		m.SetCompletionAcceptedPredictionTokens(*v)
	}
	if i.ClearCompletionRejectedPredictionTokens {
		m.ClearCompletionRejectedPredictionTokens()
	}
	if v := i.CompletionRejectedPredictionTokens; v != nil {
		m.SetCompletionRejectedPredictionTokens(*v)
	}
	if i.ClearTotalCost {
		m.ClearTotalCost()
	}
	if v := i.TotalCost; v != nil {
		m.SetTotalCost(*v)
	}
	if i.ClearCostItems {
		m.ClearCostItems()
	}
	if v := i.CostItems; v != nil {
		m.SetCostItems(v)
	}
	if i.AppendCostItems != nil {
		m.AppendCostItems(i.CostItems)
	}
	if i.ClearCostPriceReferenceID {
		m.ClearCostPriceReferenceID()
	}
	if v := i.CostPriceReferenceID; v != nil {
		m.SetCostPriceReferenceID(*v)
	}
}

// SetInput applies the change-set in the UpdateUsageLogInput on the UsageLogUpdate builder.
func (c *UsageLogUpdate) SetInput(i UpdateUsageLogInput) *UsageLogUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateUsageLogInput on the UsageLogUpdateOne builder.
func (c *UsageLogUpdateOne) SetInput(i UpdateUsageLogInput) *UsageLogUpdateOne {
	i.Mutate(c.Mutation())
	return c
}
