// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (_m *APIKey) Requests(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RequestOrder, where *RequestWhereInput,
) (*RequestConnection, error) {
	opts := []RequestPaginateOption{
		WithRequestOrder(orderBy),
		WithRequestFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[0][alias]
	if nodes, err := _m.NamedRequests(alias); err == nil || hasTotalCount {
		pager, err := newRequestPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RequestConnection{Edges: []*RequestEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryRequests().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Channel) Requests(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RequestOrder, where *RequestWhereInput,
) (*RequestConnection, error) {
	opts := []RequestPaginateOption{
		WithRequestOrder(orderBy),
		WithRequestFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[0][alias]
	if nodes, err := _m.NamedRequests(alias); err == nil || hasTotalCount {
		pager, err := newRequestPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RequestConnection{Edges: []*RequestEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryRequests().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Channel) Executions(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RequestExecutionOrder, where *RequestExecutionWhereInput,
) (*RequestExecutionConnection, error) {
	opts := []RequestExecutionPaginateOption{
		WithRequestExecutionOrder(orderBy),
		WithRequestExecutionFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[1][alias]
	if nodes, err := _m.NamedExecutions(alias); err == nil || hasTotalCount {
		pager, err := newRequestExecutionPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RequestExecutionConnection{Edges: []*RequestExecutionEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryExecutions().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Channel) UsageLogs(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UsageLogOrder, where *UsageLogWhereInput,
) (*UsageLogConnection, error) {
	opts := []UsageLogPaginateOption{
		WithUsageLogOrder(orderBy),
		WithUsageLogFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[2][alias]
	if nodes, err := _m.NamedUsageLogs(alias); err == nil || hasTotalCount {
		pager, err := newUsageLogPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UsageLogConnection{Edges: []*UsageLogEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryUsageLogs().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Channel) ChannelProbes(ctx context.Context) (result []*ChannelProbe, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedChannelProbes(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.ChannelProbesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryChannelProbes().All(ctx)
	}
	return result, err
}

func (_m *Channel) ChannelModelPrices(ctx context.Context) (result []*ChannelModelPrice, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedChannelModelPrices(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.ChannelModelPricesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryChannelModelPrices().All(ctx)
	}
	return result, err
}

func (_m *Channel) ProviderQuotaStatus(ctx context.Context) (*ProviderQuotaStatus, error) {
	result, err := _m.Edges.ProviderQuotaStatusOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryProviderQuotaStatus().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *ChannelModelPrice) Channel(ctx context.Context) (*Channel, error) {
	result, err := _m.Edges.ChannelOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryChannel().Only(ctx)
	}
	return result, err
}

func (_m *ChannelModelPrice) Versions(ctx context.Context) (result []*ChannelModelPriceVersion, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedVersions(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.VersionsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryVersions().All(ctx)
	}
	return result, err
}

func (_m *ChannelModelPriceVersion) ChannelModelPrice(ctx context.Context) (*ChannelModelPrice, error) {
	result, err := _m.Edges.ChannelModelPriceOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryChannelModelPrice().Only(ctx)
	}
	return result, err
}

func (_m *ChannelProbe) Channel(ctx context.Context) (*Channel, error) {
	result, err := _m.Edges.ChannelOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryChannel().Only(ctx)
	}
	return result, err
}

func (_m *ProviderQuotaStatus) Channel(ctx context.Context) (*Channel, error) {
	result, err := _m.Edges.ChannelOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryChannel().Only(ctx)
	}
	return result, err
}

func (_m *Request) APIKey(ctx context.Context) (*APIKey, error) {
	result, err := _m.Edges.APIKeyOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryAPIKey().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Request) Executions(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RequestExecutionOrder, where *RequestExecutionWhereInput,
) (*RequestExecutionConnection, error) {
	opts := []RequestExecutionPaginateOption{
		WithRequestExecutionOrder(orderBy),
		WithRequestExecutionFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[1][alias]
	if nodes, err := _m.NamedExecutions(alias); err == nil || hasTotalCount {
		pager, err := newRequestExecutionPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RequestExecutionConnection{Edges: []*RequestExecutionEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryExecutions().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Request) Channel(ctx context.Context) (*Channel, error) {
	result, err := _m.Edges.ChannelOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryChannel().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Request) UsageLogs(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UsageLogOrder, where *UsageLogWhereInput,
) (*UsageLogConnection, error) {
	opts := []UsageLogPaginateOption{
		WithUsageLogOrder(orderBy),
		WithUsageLogFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[3][alias]
	if nodes, err := _m.NamedUsageLogs(alias); err == nil || hasTotalCount {
		pager, err := newUsageLogPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UsageLogConnection{Edges: []*UsageLogEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryUsageLogs().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *RequestExecution) Request(ctx context.Context) (*Request, error) {
	result, err := _m.Edges.RequestOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryRequest().Only(ctx)
	}
	return result, err
}

func (_m *RequestExecution) Channel(ctx context.Context) (*Channel, error) {
	result, err := _m.Edges.ChannelOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryChannel().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *UsageLog) Request(ctx context.Context) (*Request, error) {
	result, err := _m.Edges.RequestOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryRequest().Only(ctx)
	}
	return result, err
}

func (_m *UsageLog) Channel(ctx context.Context) (*Channel, error) {
	result, err := _m.Edges.ChannelOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryChannel().Only(ctx)
	}
	return result, MaskNotFound(err)
}
