// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// APIKey is the predicate function for apikey builders.
type APIKey func(*sql.Selector)

// Channel is the predicate function for channel builders.
type Channel func(*sql.Selector)

// ChannelModelPrice is the predicate function for channelmodelprice builders.
type ChannelModelPrice func(*sql.Selector)

// ChannelModelPriceVersion is the predicate function for channelmodelpriceversion builders.
type ChannelModelPriceVersion func(*sql.Selector)

// ChannelOverrideTemplate is the predicate function for channeloverridetemplate builders.
type ChannelOverrideTemplate func(*sql.Selector)

// ChannelProbe is the predicate function for channelprobe builders.
type ChannelProbe func(*sql.Selector)

// Model is the predicate function for model builders.
type Model func(*sql.Selector)

// ProviderQuotaStatus is the predicate function for providerquotastatus builders.
type ProviderQuotaStatus func(*sql.Selector)

// Request is the predicate function for request builders.
type Request func(*sql.Selector)

// RequestExecution is the predicate function for requestexecution builders.
type RequestExecution func(*sql.Selector)

// System is the predicate function for system builders.
type System func(*sql.Selector)

// UsageLog is the predicate function for usagelog builders.
type UsageLog func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
