package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"entgo.io/contrib/entgql"
	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/log"
	"github.com/looplj/axonhub/internal/objects"
	"github.com/samber/lo"
)

// ID is the resolver for the id field.
func (r *aPIKeyResolver) ID(ctx context.Context, obj *ent.APIKey) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeAPIKey,
		ID:   obj.ID,
	}, nil
}

// ID is the resolver for the id field.
func (r *channelResolver) ID(ctx context.Context, obj *ent.Channel) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeChannel,
		ID:   obj.ID,
	}, nil
}

// Policies is the resolver for the policies field.
// It is used to return the default value if the field is not set.
func (r *channelResolver) Policies(ctx context.Context, obj *ent.Channel) (*objects.ChannelPolicies, error) {
	if obj.Policies.Stream == "" {
		obj.Policies.Stream = objects.CapabilityPolicyUnlimited
	}

	return &obj.Policies, nil
}

// ProviderQuotaStatus is the resolver for the providerQuotaStatus field.
// It returns null (not an error) when no quota status exists for the channel.
func (r *channelResolver) ProviderQuotaStatus(ctx context.Context, obj *ent.Channel) (*ent.ProviderQuotaStatus, error) {
	pqs, err := obj.ProviderQuotaStatus(ctx)
	if ent.IsNotFound(err) {
		return nil, nil
	}

	return pqs, err
}

// ID is the resolver for the id field.
func (r *channelModelPriceResolver) ID(ctx context.Context, obj *ent.ChannelModelPrice) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeChannelModelPrice,
		ID:   obj.ID,
	}, nil
}

// ChannelID is the resolver for the channelID field.
func (r *channelModelPriceResolver) ChannelID(ctx context.Context, obj *ent.ChannelModelPrice) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeChannel,
		ID:   obj.ChannelID,
	}, nil
}

// ID is the resolver for the id field.
func (r *channelModelPriceVersionResolver) ID(ctx context.Context, obj *ent.ChannelModelPriceVersion) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeChannelModelPriceVersion,
		ID:   obj.ID,
	}, nil
}

// ChannelModelPriceID is the resolver for the channelModelPriceID field.
func (r *channelModelPriceVersionResolver) ChannelModelPriceID(ctx context.Context, obj *ent.ChannelModelPriceVersion) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeChannelModelPrice,
		ID:   obj.ChannelModelPriceID,
	}, nil
}

// ID is the resolver for the id field.
func (r *channelOverrideTemplateResolver) ID(ctx context.Context, obj *ent.ChannelOverrideTemplate) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeChannelOverrideTemplate,
		ID:   obj.ID,
	}, nil
}

// HeaderOverrideOperations is the resolver for the headerOverrideOperations field.
// It returns the new header override operations, converting from legacy OverrideHeaders if needed.
func (r *channelOverrideTemplateResolver) HeaderOverrideOperations(ctx context.Context, obj *ent.ChannelOverrideTemplate) ([]*objects.OverrideOperation, error) {
	// If new field has data, use it directly
	if len(obj.HeaderOverrideOperations) > 0 {
		return lo.ToSlicePtr(obj.HeaderOverrideOperations), nil
	}

	// Convert from legacy OverrideHeaders field
	if len(obj.OverrideHeaders) > 0 {
		ops := objects.HeaderEntriesToOverrideOperations(obj.OverrideHeaders)
		return lo.ToSlicePtr(ops), nil
	}

	return []*objects.OverrideOperation{}, nil
}

// BodyOverrideOperations is the resolver for the bodyOverrideOperations field.
// It returns the new body override operations, converting from legacy OverrideParameters if needed.
func (r *channelOverrideTemplateResolver) BodyOverrideOperations(ctx context.Context, obj *ent.ChannelOverrideTemplate) ([]*objects.OverrideOperation, error) {
	// If new field has data, use it directly
	if len(obj.BodyOverrideOperations) > 0 {
		return lo.ToSlicePtr(obj.BodyOverrideOperations), nil
	}

	// Convert from legacy OverrideParameters field
	if obj.OverrideParameters != "" && obj.OverrideParameters != "{}" {
		ops, err := objects.ParseOverrideOperations(obj.OverrideParameters)
		if err != nil {
			return nil, fmt.Errorf("failed to parse override parameters: %w", err)
		}

		return lo.ToSlicePtr(ops), nil
	}

	return []*objects.OverrideOperation{}, nil
}

// ID is the resolver for the id field.
func (r *channelProbeResolver) ID(ctx context.Context, obj *ent.ChannelProbe) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeChannelProbe,
		ID:   obj.ID,
	}, nil
}

// ChannelID is the resolver for the channelID field.
func (r *channelProbeResolver) ChannelID(ctx context.Context, obj *ent.ChannelProbe) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeChannel,
		ID:   obj.ChannelID,
	}, nil
}

// ID is the resolver for the id field.
func (r *modelResolver) ID(ctx context.Context, obj *ent.Model) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeModel,
		ID:   obj.ID,
	}, nil
}

// ID is the resolver for the id field.
func (r *providerQuotaStatusResolver) ID(ctx context.Context, obj *ent.ProviderQuotaStatus) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeProviderQuotaStatus,
		ID:   obj.ID,
	}, nil
}

// ChannelID is the resolver for the channelID field.
func (r *providerQuotaStatusResolver) ChannelID(ctx context.Context, obj *ent.ProviderQuotaStatus) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeChannel,
		ID:   obj.ChannelID,
	}, nil
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id objects.GUID) (ent.Noder, error) {
	typ, ok := guidTypeToNodeType[id.Type]
	if !ok {
		return nil, fmt.Errorf("unknown node type: %s", id.Type)
	}

	return r.client.Noder(ctx, id.ID, ent.WithFixedNodeType(typ))
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []*objects.GUID) ([]ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Nodes - nodes"))
}

// APIKeys is the resolver for the apiKeys field.
func (r *queryResolver) APIKeys(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, orderBy *ent.APIKeyOrder, where *ent.APIKeyWhereInput) (*ent.APIKeyConnection, error) {
	if err := validatePaginationArgs(first, last); err != nil {
		return nil, err
	}

	if orderBy != nil && orderBy.Field.String() == "CREATED_AT" {
		orderBy.Field = ent.DefaultAPIKeyOrder.Field
	}

	return r.client.APIKey.Query().Paginate(ctx, after, first, before, last,
		ent.WithAPIKeyOrder(orderBy),
		ent.WithAPIKeyFilter(where.Filter),
	)
}

// Channels is the resolver for the channels field.
func (r *queryResolver) Channels(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, orderBy *ent.ChannelOrder, where *ent.ChannelWhereInput) (*ent.ChannelConnection, error) {
	if orderBy != nil && orderBy.Field.String() == "CREATED_AT" {
		orderBy.Field = ent.DefaultChannelOrder.Field
	}

	return r.client.Channel.Query().Paginate(ctx, after, first, before, last,
		ent.WithChannelOrder(orderBy),
		ent.WithChannelFilter(where.Filter),
	)
}

// ChannelOverrideTemplates is the resolver for the channelOverrideTemplates field.
func (r *queryResolver) ChannelOverrideTemplates(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, orderBy *ent.ChannelOverrideTemplateOrder, where *ent.ChannelOverrideTemplateWhereInput) (*ent.ChannelOverrideTemplateConnection, error) {
	if err := validatePaginationArgs(first, last); err != nil {
		return nil, err
	}

	if orderBy != nil && orderBy.Field.String() == "CREATED_AT" {
		orderBy.Field = ent.DefaultChannelOverrideTemplateOrder.Field
	}

	return r.client.ChannelOverrideTemplate.Query().Paginate(ctx, after, first, before, last,
		ent.WithChannelOverrideTemplateOrder(orderBy),
		ent.WithChannelOverrideTemplateFilter(where.Filter),
	)
}

// Models is the resolver for the models field.
func (r *queryResolver) Models(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, orderBy *ent.ModelOrder, where *ent.ModelWhereInput) (*ent.ModelConnection, error) {
	if orderBy != nil && orderBy.Field.String() == "CREATED_AT" {
		orderBy.Field = ent.DefaultModelOrder.Field
	}
	return r.client.Model.Query().Paginate(ctx, after, first, before, last,
		ent.WithModelOrder(orderBy),
		ent.WithModelFilter(where.Filter),
	)
}

// Requests is the resolver for the requests field.
func (r *queryResolver) Requests(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, orderBy *ent.RequestOrder, where *ent.RequestWhereInput) (*ent.RequestConnection, error) {
	if err := validatePaginationArgs(first, last); err != nil {
		return nil, err
	}

	if orderBy != nil && orderBy.Field.String() == "CREATED_AT" {
		orderBy.Field = ent.DefaultRequestOrder.Field
	}

	return r.client.Request.Query().Paginate(ctx, after, first, before, last,
		ent.WithRequestOrder(orderBy),
		ent.WithRequestFilter(where.Filter),
	)
}

// Systems is the resolver for the systems field.
func (r *queryResolver) Systems(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, orderBy *ent.SystemOrder, where *ent.SystemWhereInput) (*ent.SystemConnection, error) {
	if err := validatePaginationArgs(first, last); err != nil {
		return nil, err
	}

	return r.client.System.Query().Paginate(ctx, after, first, before, last,
		ent.WithSystemOrder(orderBy),
		ent.WithSystemFilter(where.Filter),
	)
}

// UsageLogs is the resolver for the usageLogs field.
func (r *queryResolver) UsageLogs(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, orderBy *ent.UsageLogOrder, where *ent.UsageLogWhereInput) (*ent.UsageLogConnection, error) {
	if err := validatePaginationArgs(first, last); err != nil {
		return nil, err
	}

	if orderBy != nil && orderBy.Field.String() == "CREATED_AT" {
		orderBy.Field = ent.DefaultUsageLogOrder.Field
	}

	return r.client.UsageLog.Query().Paginate(ctx, after, first, before, last,
		ent.WithUsageLogOrder(orderBy),
		ent.WithUsageLogFilter(where.Filter),
	)
}

// ID is the resolver for the id field.
func (r *requestResolver) ID(ctx context.Context, obj *ent.Request) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeRequest,
		ID:   obj.ID,
	}, nil
}

// APIKeyID is the resolver for the apiKeyID field.
func (r *requestResolver) APIKeyID(ctx context.Context, obj *ent.Request) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeAPIKey,
		ID:   obj.APIKeyID,
	}, nil
}

// RequestBody is the resolver for the requestBody field.
func (r *requestResolver) RequestBody(ctx context.Context, obj *ent.Request) (objects.JSONRawMessage, error) {
	value, err := r.requestService.LoadRequestBody(ctx, obj)
	if err != nil {
		log.Error(ctx, "Failed to load request body", log.Cause(err), log.Int("request_id", obj.ID))
		return nil, fmt.Errorf("failed to load request body: %w", err)
	}

	return value, nil
}

// ResponseBody is the resolver for the responseBody field.
func (r *requestResolver) ResponseBody(ctx context.Context, obj *ent.Request) (objects.JSONRawMessage, error) {
	value, err := r.requestService.LoadResponseBody(ctx, obj)
	if err != nil {
		log.Error(ctx, "Failed to load request response body", log.Cause(err), log.Int("request_id", obj.ID))
		return nil, fmt.Errorf("failed to load response body: %w", err)
	}

	return value, nil
}

// ResponseChunks is the resolver for the responseChunks field.
func (r *requestResolver) ResponseChunks(ctx context.Context, obj *ent.Request) ([]objects.JSONRawMessage, error) {
	value, err := r.requestService.LoadResponseChunks(ctx, obj)
	if err != nil {
		log.Error(ctx, "Failed to load request response chunks", log.Cause(err), log.Int("request_id", obj.ID))

		// GraphQL requires slices to be non-nil; return empty slice with error
		return []objects.JSONRawMessage{}, fmt.Errorf("failed to load response chunks: %w", err)
	}

	if value == nil {
		return []objects.JSONRawMessage{}, nil
	}

	return value, nil
}

// ChannelID is the resolver for the channelID field.
func (r *requestResolver) ChannelID(ctx context.Context, obj *ent.Request) (*objects.GUID, error) {
	if obj.ChannelID == 0 {
		//nolint:nilnil // Checked.
		return nil, nil
	}

	return &objects.GUID{
		Type: ent.TypeChannel,
		ID:   obj.ChannelID,
	}, nil
}

// Channel is the resolver for the channel field.
func (r *requestResolver) Channel(ctx context.Context, obj *ent.Request) (*ent.Channel, error) {
	return getNilableChannel(ctx, r.client, obj.ChannelID)
}

// ID is the resolver for the id field.
func (r *requestExecutionResolver) ID(ctx context.Context, obj *ent.RequestExecution) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeRequestExecution,
		ID:   obj.ID,
	}, nil
}

// RequestID is the resolver for the requestID field.
func (r *requestExecutionResolver) RequestID(ctx context.Context, obj *ent.RequestExecution) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeRequest,
		ID:   obj.RequestID,
	}, nil
}

// ChannelID is the resolver for the channelID field.
func (r *requestExecutionResolver) ChannelID(ctx context.Context, obj *ent.RequestExecution) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeChannel,
		ID:   obj.ChannelID,
	}, nil
}

// RequestBody is the resolver for the requestBody field.
func (r *requestExecutionResolver) RequestBody(ctx context.Context, obj *ent.RequestExecution) (objects.JSONRawMessage, error) {
	value, err := r.requestService.LoadRequestExecutionRequestBody(ctx, obj)
	if err != nil {
		log.Error(ctx, "Failed to load execution request body", log.Cause(err), log.Int("request_execution_id", obj.ID))
		return nil, fmt.Errorf("failed to load request body: %w", err)
	}

	return value, nil
}

// ResponseBody is the resolver for the responseBody field.
func (r *requestExecutionResolver) ResponseBody(ctx context.Context, obj *ent.RequestExecution) (objects.JSONRawMessage, error) {
	value, err := r.requestService.LoadRequestExecutionResponseBody(ctx, obj)
	if err != nil {
		log.Error(ctx, "Failed to load execution response body", log.Cause(err), log.Int("request_execution_id", obj.ID))
		return nil, fmt.Errorf("failed to load response body: %w", err)
	}

	return value, nil
}

// ResponseChunks is the resolver for the responseChunks field.
func (r *requestExecutionResolver) ResponseChunks(ctx context.Context, obj *ent.RequestExecution) ([]objects.JSONRawMessage, error) {
	value, err := r.requestService.LoadRequestExecutionResponseChunks(ctx, obj)
	if err != nil {
		log.Error(ctx, "Failed to load execution response chunks", log.Cause(err), log.Int("request_execution_id", obj.ID))
		return []objects.JSONRawMessage{}, fmt.Errorf("failed to load response chunks: %w", err)
	}

	if value == nil {
		return []objects.JSONRawMessage{}, nil
	}

	return value, nil
}

// Channel is the resolver for the channel field.
func (r *requestExecutionResolver) Channel(ctx context.Context, obj *ent.RequestExecution) (*ent.Channel, error) {
	return getNilableChannel(ctx, r.client, obj.ChannelID)
}

// ID is the resolver for the id field.
func (r *systemResolver) ID(ctx context.Context, obj *ent.System) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeSystem,
		ID:   obj.ID,
	}, nil
}

// ID is the resolver for the id field.
func (r *usageLogResolver) ID(ctx context.Context, obj *ent.UsageLog) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeUsageLog,
		ID:   obj.ID,
	}, nil
}

// RequestID is the resolver for the requestID field.
func (r *usageLogResolver) RequestID(ctx context.Context, obj *ent.UsageLog) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeRequest,
		ID:   obj.RequestID,
	}, nil
}

// ChannelID is the resolver for the channelID field.
func (r *usageLogResolver) ChannelID(ctx context.Context, obj *ent.UsageLog) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeChannel,
		ID:   obj.ChannelID,
	}, nil
}

// Channel is the resolver for the channel field.
func (r *usageLogResolver) Channel(ctx context.Context, obj *ent.UsageLog) (*ent.Channel, error) {
	return getNilableChannel(ctx, r.client, obj.ChannelID)
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *ent.User) (*objects.GUID, error) {
	return &objects.GUID{
		Type: ent.TypeUser,
		ID:   obj.ID,
	}, nil
}

// APIKey returns APIKeyResolver implementation.
func (r *Resolver) APIKey() APIKeyResolver { return &aPIKeyResolver{r} }

// Channel returns ChannelResolver implementation.
func (r *Resolver) Channel() ChannelResolver { return &channelResolver{r} }

// ChannelModelPrice returns ChannelModelPriceResolver implementation.
func (r *Resolver) ChannelModelPrice() ChannelModelPriceResolver {
	return &channelModelPriceResolver{r}
}

// ChannelModelPriceVersion returns ChannelModelPriceVersionResolver implementation.
func (r *Resolver) ChannelModelPriceVersion() ChannelModelPriceVersionResolver {
	return &channelModelPriceVersionResolver{r}
}

// ChannelOverrideTemplate returns ChannelOverrideTemplateResolver implementation.
func (r *Resolver) ChannelOverrideTemplate() ChannelOverrideTemplateResolver {
	return &channelOverrideTemplateResolver{r}
}

// ChannelProbe returns ChannelProbeResolver implementation.
func (r *Resolver) ChannelProbe() ChannelProbeResolver { return &channelProbeResolver{r} }

// Model returns ModelResolver implementation.
func (r *Resolver) Model() ModelResolver { return &modelResolver{r} }

// ProviderQuotaStatus returns ProviderQuotaStatusResolver implementation.
func (r *Resolver) ProviderQuotaStatus() ProviderQuotaStatusResolver {
	return &providerQuotaStatusResolver{r}
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Request returns RequestResolver implementation.
func (r *Resolver) Request() RequestResolver { return &requestResolver{r} }

// RequestExecution returns RequestExecutionResolver implementation.
func (r *Resolver) RequestExecution() RequestExecutionResolver { return &requestExecutionResolver{r} }

// System returns SystemResolver implementation.
func (r *Resolver) System() SystemResolver { return &systemResolver{r} }

// UsageLog returns UsageLogResolver implementation.
func (r *Resolver) UsageLog() UsageLogResolver { return &usageLogResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type aPIKeyResolver struct{ *Resolver }
type channelResolver struct{ *Resolver }
type channelModelPriceResolver struct{ *Resolver }
type channelModelPriceVersionResolver struct{ *Resolver }
type channelOverrideTemplateResolver struct{ *Resolver }
type channelProbeResolver struct{ *Resolver }
type modelResolver struct{ *Resolver }
type providerQuotaStatusResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type requestResolver struct{ *Resolver }
type requestExecutionResolver struct{ *Resolver }
type systemResolver struct{ *Resolver }
type usageLogResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
