
type UserInfo {
  id: ID!
  email: String!
  firstName: String!
  lastName: String!
  isOwner: Boolean!
  preferLanguage: String!
  avatar: String
  hasPassword: Boolean!
}

extend type Query {
    me: UserInfo!
}

input UpdateMeInput {
  firstName: String
  lastName: String
  preferLanguage: String
  avatar: String
}

extend type Mutation {
    updateMe(input: UpdateMeInput!): User!
    updateMyPassword(input: UpdateMyPasswordInput!): Boolean!
}

input UpdateMyPasswordInput {
  oldPassword: String
  newPassword: String!
}
