package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/looplj/axonhub/internal/contexts"
	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/server/biz"
)

// UpdateMe is the resolver for the updateMe field.
func (r *mutationResolver) UpdateMe(ctx context.Context, input UpdateMeInput) (*ent.User, error) {
	// Get current user from context
	user, ok := contexts.GetUser(ctx)
	if !ok || user == nil {
		return nil, fmt.Errorf("user not found in context")
	}

	return r.userService.UpdateUser(ctx, user.ID, biz.UpdateUserInput{
		FirstName:      input.FirstName,
		LastName:       input.LastName,
		PreferLanguage: input.PreferLanguage,
		Avatar:         input.Avatar,
	})
}

// UpdateMyPassword is the resolver for the updateMyPassword field.
func (r *mutationResolver) UpdateMyPassword(ctx context.Context, input UpdateMyPasswordInput) (bool, error) {
	// Get current user from context
	user, ok := contexts.GetUser(ctx)
	if !ok || user == nil {
		return false, fmt.Errorf("user not found in context")
	}

	if input.OldPassword == nil {
		return false, fmt.Errorf("current password is required")
	}

	err := biz.VerifyPassword(user.Password, *input.OldPassword)
	if err != nil {
		return false, fmt.Errorf("incorrect old password")
	}

	_, err = r.userService.UpdateUser(ctx, user.ID, biz.UpdateUserInput{
		Password: &input.NewPassword,
	})
	if err != nil {
		return false, err
	}

	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*objects.UserInfo, error) {
	// Get current user from context
	userCtx, ok := contexts.GetUser(ctx)
	if !ok || userCtx == nil {
		return nil, fmt.Errorf("user not found in context")
	}

	// Fetch the full user model with all preloaded edges
	user, err := r.userService.GetUserByID(ctx, userCtx.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to get user details: %w", err)
	}

	// Use UserService to convert user to UserInfo
	return biz.ConvertUserToUserInfo(ctx, user), nil
}
